### ISSUE TITLE
SSBなどの信頼区間の表

### ISSUE THREAD

**Issue by ShotaNishijima** [ichimomo/frasyr#112]
資源評価票で必要なbetaごとの信頼区間の表を出力できるようにする

**Comment by akikirinrin** [comment]
ありがとうございます

**Comment by ichimomo** [comment]
信頼区間の表の出力については，暫定的にはこちらの修正で対応しています．
https://github.com/ichimomo/frasyr/commit/c0fb3e6b957d2b09f123102d51b834d5d5c11040
→　out.vpaに追加
https://github.com/ichimomo/frasyr_tool/commit/088efaeacf76faf318441bf8e5d981be8bdbcf1e
→　そのバージョンに対応したfrasyr_toolを更新
実際には，これらからもっとコミット進んでいますので，最新版で対応できているはずです．

ただ，ダイレクトに資源評価票にコピペできるかたちで表を出力するようになったらもっと便利だと思いますので，そのような表の実装のほうを想定されているようでしたら，ウェルカムです．

**Comment by ShotaNishijima** [comment]
ありがとうございます。betaだけではなく、Fcurrentでの信頼区間も必要なんですが、それも出るようになっているでしょうか？僕はなるべく資源評価票にそのまま使えそうに、以下のようなコードを書きました。あと、漁獲割合も表に記入すべきところがあるので、平均漁獲割合を出力してくれると助かります。

SSB2030_ci = kobeII.data %>% filter(year == 2030 & stat=="SSB") %>%
  mutate(value = value/1000) %>%
  group_by(HCR_name, beta) %>%
  summarise(Mean = mean(value), Median = median(value),
            Lower80= quantile(value, prob=0.1), Upper80=quantile(value, prob=0.9),
            Lower90= quantile(value, prob=0.05), Upper90=quantile(value, prob=0.95),
            Lower95= quantile(value, prob=0.025), Upper95=quantile(value, prob=0.975),
            CV = sd(value)/mean(value),
            prob_SBtarget = mean(value>Btarget_update/1000),
            prob_SBlimit = mean(value>Blimit_update/1000),
            prob_SBban = mean(value>Bban_update/1000)) %>%
  mutate(F_name = "HCR") %>%
  select(F_name,everything())

SSB2030_Fcur = res_future_current$vssb["2030",]/1000
if (det_run ) SSB2030_Fcur = SSB2030_Fcur[-1]

SSB2030_ci = bind_rows(SSB2030_ci,
                       tibble(F_name="Fcurrent",HCR_name=NA,beta=NA,
                              Mean = mean(SSB2030_Fcur),Median = median(SSB2030_Fcur),
                              Lower80= quantile(SSB2030_Fcur, prob=0.1), Upper80=quantile(SSB2030_Fcur, prob=0.9),
                              Lower90= quantile(SSB2030_Fcur, prob=0.05), Upper90=quantile(SSB2030_Fcur, prob=0.95),
                              Lower95= quantile(SSB2030_Fcur, prob=0.025), Upper95=quantile(SSB2030_Fcur, prob=0.975),
                              CV = sd(SSB2030_Fcur)/mean(SSB2030_Fcur),
                              prob_SBtarget = mean(SSB2030_Fcur>Btarget_update/1000),
                              prob_SBlimit = mean(SSB2030_Fcur>Blimit_update/1000),
                              prob_SBban = mean(SSB2030_Fcur>Bban_update/1000)))

write.csv(SSB2030_ci, file = "SSB2030_ci.csv")

**Comment by ichimomo** [comment]
承知しました，これらのコードを参考にして，
資源評価票で必要な出力を最後に出すような感じに修正します．

**Comment by ichimomo** [comment]
https://github.com/ichimomo/frasyr/commit/e7b137533ad4eae819b985e9c2af6f988e061f17
https://github.com/ichimomo/frasyr_tool/commit/c02506e4328a4c320ff8d35081efba89a79cac6b

こちらの2つの更新で対応したと思います．
なにかエラーなどありましたらご報告ください．

**Comment by ShotaNishijima** [comment]
ありがとうございました。
