### ISSUE TITLE
plot_HCRを資源評価票に使えるように

### ISSUE THREAD

**Issue by ShotaNishijima** [ichimomo/frasyr#114]
#113  にてplot_HCRのラベルをオフにして、後から加えられるようにしたのですが、資源評価票に載せる図も作れるように、もうちょっと柔軟に図が描けるように関数を修正してもらえないでしょうか？僕は以下のような感じで書いてみました

(gg_hcr = plot_HCR(SBtarget = Btarget_update,SBlim = Blimit_update,
                  SBban = Bban_update,Ftarget=Ftarget,beta=0.8,
                  biomass.unit = 1000, is.text = FALSE)+
    ylab("現状の漁獲圧に対する比")+
    ylim(NA,0.7)+
    annotate("text", label="SBtarget=SBmsy", x=Btarget_update/1000, y=1.2*Ftarget,colour="#00533E",hjust=0,vjust=0)+
    annotate("text", label="SBlimit=SB0.6msy", x=Blimit_update/1000, y=1.1*Ftarget,colour="#edb918",hjust=0,vjust=1)+
    annotate("text", label="SBban=SB0.1msy", x=Bban_update/1000, y=1.2*Ftarget,colour="#C73C2E",hjust=0,vjust=0)+
    annotate("text", label="Fmsy", x=1.3*Btarget_update/1000, y=0.95*Ftarget,colour="black",vjust=1)+
    annotate("text", label=expression(beta*Fmsy), x=1.3*Btarget_update/1000, y=0.95*0.8*Ftarget,colour="black",vjust=1)
  )

**Comment by ichimomo** [comment]
こちらは福井さんが作ってくれた関数なので，そちらにおまかせしてしまってもよいでしょうか？
よろしくお願いします．
