### ISSUE TITLE
check()におけるplot_yieldのエラー

### ISSUE THREAD

**Issue by ShotaNishijima** [ichimomo/frasyr#121]
https://github.com/ichimomo/frasyr/blob/8951d82f779eb40189af82359b8d605058497a9c/R/utilities.r#L271

ここで「年齢」を使ってるせいで、Windows環境だとcheck()が通らない。

**Comment by ichimomo** [comment]
この問題どうなりました？もし現状の環境でcheck通っているのであればcloseしてもらっても良いでしょうか？

**Comment by ShotaNishijima** [comment]
エラー出たままです。しかし、それでも一応、checkは最後まで行くので、気にしないでやっています。
