### ISSUE TITLE
masterを保護する

### ISSUE THREAD

**Issue by akikirinrin** [ichimomo/frasyr#131]
いつもの手順で、masterを改変できるのはプルリクのみにしてください

**Comment by ichimomo** [comment]
対応しました．
このタイミングで，11月27日会議バージョンとしてdevブランチもmasterにmergeしようかと思います．

**Comment by ichimomo** [comment]
masterを「保護」する設定って，「マージする前にreviewを必要とする　Require pull request reviews before merging」くらいしか該当するようなものがないような気がするのですがこの設定以外に何かありますか？これだと誰かにreviewをassignしないとマージできない設定になってしまってちょっと面倒くさいのですが．．．

**Comment by akikirinrin** [comment]
ありがとうございます！
むしろ、どこもチェックつけなければ、レビューはいらないと思いますよ
