### ISSUE TITLE
VPAのモデル診断手順の確立

### ISSUE THREAD

**Issue by ichimomo** [ichimomo/frasyr#136]
ＶＰＡのモデル診断を網羅的に実施するためのＲの関数，スクリプトを作っていただけないでしょうか？特に，資源量指数を使ってチューニングする場合について

・残差（log(観測値)-log(予測値)の時系列プロット，右上にσの値，3σの値で横線を引く
・横軸に資源量，縦軸に資源量指数をとったときの両者の関係．CPUE=q x 資源量^bの線も示す
・ブートストラップを実施し，信頼区間を示す
・レトロスペクティブ解析を実施し，その結果を示す

以上のような解析・結果のグラフをすぐ出力するようなスクリプトがほしいです．

**Comment by ShotaNishijima** [comment]
僕が書いた関数がABC2019のnishijimaブランチの中にいくつかの関数があるので、ちょっと修正すれば使えるかもしれません。
https://github.com/ichimomo/ABC2019/blob/nishijima/masaba-Pacific/original-function1.0.r

・残差プロット(resid.plot)
・横軸に資源量，縦軸に資源量指数をとったときの両者の関係 (nl.plot)．
・レトロスペクティブ解析のプロット(biom.retro.plotなど)

は一応あります。ただし、ggplotを知らないときに書いたので修正した方がいいかもしれません。参考までに。

**Comment by ShotaNishijima** [comment]
あと、トラフグの資源評価のときにブートストラップとレトロのプロットをggplotで描いていたので、そのときのコードも添付しておきます。

[tfg_figure_ver2.txt](https://github.com/ichimomo/frasyr/files/3901461/tfg_figure_ver2.txt)


``

**Comment by ichimomo** [comment]
とりあえず，複数のVPA結果を重ね書きする一般関数を作りました．

https://github.com/ichimomo/frasyr/wiki/frasyr%E6%96%B0%E6%A9%9F%E8%83%BD%EF%BC%9Acheat-sheet#plot_vpa

こちらを使っていただければレトロの可視化は簡単にできるかと思います．
レトロやブートストラップをどうやってやるかは西嶋さんのコードを参照してください．

**Comment by KoheiHAMABE** [comment]
モデル診断スクリプト完成したのでcloseします
