### ISSUE TITLE
rvpa課題

### ISSUE THREAD

**Issue by OkamuraHiroshi** [ichimomo/frasyr#139]
1. q, b, sigmaの制約をおいて自由に推定できるようにする．TMBで書くのが望ましい．

2. rvpa_tmbで，Popeの近似式でなく，Baranov方程式でできるようにする

3. retro patternのグラフ描画関数作成

**Comment by ichimomo** [comment]
issueありがとうございます．３つのissue，それぞれに分けても良いですか？

**Comment by OkamuraHiroshi** [comment]
3つ？   分ける？

2019年11月29日(金) 9:08 Momoko Ichinokawa <notifications@github.com>:

**Comment by ichimomo** [comment]
上のように，#142, #143, #144の3つのissueに分けました．それぞれについて，だれにやってもらうか，人をアサインすることができます．#144については，#136で福井さんにアサインしているので，そちらと被りそうなので，福井さんにアサインしておきます
