### ISSUE TITLE
retro patternのグラフ描画関数作成

### ISSUE THREAD

**Issue by ichimomo** [ichimomo/frasyr#144]
issueありがとうございます．３つのissue，それぞれに分けても良いですか？

_Originally posted by @ichimomo in https://github.com/ichimomo/frasyr/issues/139#issuecomment-559622312_

**Comment by ichimomo** [comment]
#136の一部になるかなと思います

**Comment by KoheiHAMABE** [comment]
モデル診断関数完成したので、こちらクローズします
