### ISSUE TITLE
est.MSY高速化

### ISSUE THREAD

**Issue by ichimomo** [ichimomo/frasyr#150]
TMBを使って高速化する

**Comment by OkamuraHiroshi** [comment]
// HS stock-recruitment curve

#include <TMB.hpp>
#include <iostream>

template<class Type>
Type objective_function<Type>::operator() ()
{
  // DATA //
  DATA_VECTOR(R);
  DATA_VECTOR(SB);
  
  // PARAMETER //
  PARAMETER(log_a); // fixed effect
  PARAMETER(logit_b);
  PARAMETER(log_sigma);
    
  // Parameter transformation
  Type a = exp(log_a);
  Type b = (max(SB)-min(SB))/(1+exp(-logit_b))+min(SB);
  Type sigma = exp(log_sigma);
  
  Type nll=0;
  
  vector<Type> predR(SB.size());
  
  for(int i=0;i<SB.size();i++){ 
  
    Type SSB = SB(i);
    predR(i) = CppAD::CondExpLt(SSB,b,a*SSB,a*b);
    
    nll -= dnorm(log(R(i)),log(predR(i)), sigma,true);
  }
  
  ADREPORT(a);
  ADREPORT(b);
  ADREPORT(sigma);
  ADREPORT(predR);
  return nll;
}
