### ISSUE TITLE
CAAにNAが含まれる時のfuture0.csvの表示エラー

### ISSUE THREAD

**Issue by symuko** [ichimomo/frasyr#157]
プラスグループの設定変更によりCAAにNAが含まれる場合、出力ファイル"future0.csv"のSSBやBiomassテーブルがNA表記となり、結果が取得できません。

**Comment by ichimomo** [comment]
修正してみました。最新版のdevをインストールして試してみてください。
ＮＡ表示になるのはＶＰＡの結果の部分だけで良かったでしょうか？

**Comment by symuko** [comment]
早速のご対応ありがとうございます。VPA結果表示の修正、確認しました。

過去は5+だったが、現在は4+までという年齢構成の状況なので、MSYや将来予測では5+歳は考えないという理解で良いでしょうか？2doでの結果で、5+歳に関する項目は全てNA表記です。0~4歳やtotalに関する項目には全て数値が入っており、グラフの出力も問題ありません。

**Comment by ichimomo** [comment]
> MSYや将来予測では5+歳は考えないという理解で良いでしょうか？2doでの結果で、5+歳に関する項目は全てNA表記です。

現状のプログラムでは5歳以上は計算していないので、NA表記になっています。

ただ、もし、将来予測では５＋まで考えたいということであれば、プログラムのほうはそのように対応しますので、教えてください（このあたりの設定は各魚種担当の方が最適と思われる設定を考えていただければプログラムはそれに対応するようなものになるかと思います）

どうぞよろしくお願い致します。

**Comment by symuko** [comment]
ご返信ありがとうございます。将来予測の設定が確認でき、安心しました。
マイワシ対馬では、今のところ5+を復活させるという話は出ていないので、現状のプログラムで大丈夫です。
今後ともよろしくお願い致します。
