### ISSUE TITLE
devが壊れてます=>est.MSYのテストが通らない

### ISSUE THREAD

**Issue by akikirinrin** [ichimomo/frasyr#170]
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/14845847/71066736-93767580-21b6-11ea-84ed-a322fb3b1a70.png">

https://github.com/ichimomo/frasyr/commit/58065573b3a78a358fa3de76951d417600ed19f4
からだそうです

**Comment by fshin3** [comment]
多分月曜に私がプルしたので壊しました。で、火曜の夕方にrevertしてもらって戻しました。まだ壊れてますか？

**Comment by ichimomo** [comment]
たぶん私がfuture.vpaの内容を大きく変えたので、それがテストの内容と一致しなくなった
ためだと思います。テストのほうも、現在、福井さんが改訂作業中なので、
とりあえずdevに私のほうのコードをアップして、福井さんがテストの改訂作業を終わらせて
それがdevにアップされた段階で、テストでエラーが出ないように修正しようと思っております。

なので、少々お待ちください。

**Comment by akikirinrin** [comment]
既に把握されているのであればよかったです。失礼しました。closeします。

**Comment by ichimomo** [comment]
- このくらいのタイミングで通らなくなったest.MSYのテストですが，#65の変更のせいだと思います（nyear=NULLの場合の挙動が異なる）
- 3d2110c68396194ac92e02c96e3f49f0a4e5930f のコミットで，新しいest.MSYにおいて，nyear=GT*20と明示的に年数を指定して計算することで，両者のFの違いは1～3％まで減りました（が，まだ完全には一致していません）　古いest.MSYと新しいest.MSYで同じnyearを指定することで，もっと数字は一致するかもしれないです
- また，時間はかかりますが，est.MSYの引数Nは1000くらいに設定したほうが誤差が減ると思います

**Comment by ichimomo** [comment]
福井様，test1ブランチで修正したコードをアップしているので，見てみてください．

**Comment by ichimomo** [comment]
- もう一つの違いは，future2.1.r（4月くらいのest.MSY）から12月くらいまでのest.MSYまでのあいだに，future.vpa内のdet.runオプションが変わったせいです．多分このあたりの行↓が追加されています．

https://github.com/ichimomo/frasyr/blob/630166afdf21ac00d6cb9463465ada2fe46399bf/R/future.r#L1019-L1020

- 4月の段階でも，det.runオプションはあったんですが，デフォルト値のTRUEからFALSEに変えても挙動は変わりませんでした（あとで実装しようとして引数だけ作って忘れていた？）．
- 8月くらいに，det.run=FALSEにしたとき，期待通りの結果が出るように変更しました．通常の将来予測ではデフォルトの引数を使っているので影響ありませんが，est.MSYするときにはdet.run=FALSEに引数を置き換えているので，est.MSYのときの結果は変わったということです．
- 実際にはMSY推定は1000回以上のシミュレーションの平均をとっているので，十分回数実行したest.MSYの結果であれば漸近的に一致するはずではあります
- ただ，get.stat関数で1行目は計算から除いているので，影響ないはずなんですが，乱数が違っているみたいなので，そのせいかも．．．

中途半端ですみませんが．．

**Comment by ichimomo** [comment]
testだけでなくvignetteのbuildに失敗していた、ということもあったようです。とりあえずvignetteを退避することで通るようになったのでcloseします
