### ISSUE TITLE
プラットフォームに依存しない実行/開発環境の構築

### ISSUE THREAD

**Issue by AnguillaJaponica** [ichimomo/frasyr#178]
今後のシステムの構築を進める上で、実行/開発環境の差異が負債になる可能性があります。
具体的には以下をイメージしていただけるとわかりやすいです。

Windows: 文字コードの闇、C++コンパイラ、Gitまわり、等
Mac: XCodeでかい、ショートカット、homebrew前提な記事多い...、等
Ubuntu: RStudioの日本語入力問題、等
その他共通: ファイルパス、環境変数、等

一人で開発/使用していく分にはいいのですが、ユーザーが広がり、開発も分散して行うとなると、とにかくきつくて悲しい結末になります(内輪だけで使われ、公開はしているものの外部の資源管理担当者・開発者が開発に携われない/そもそも読まない)。

そこで、(ジャストアイデアですが)仮想環境を立ててそこでシステムが動くようにするのもありかなと。これにより
・開発の前提が統一される
・WinやMac、Linuxなど、どの環境でもノーストレスで利用できるようになる
・作った環境をすぐにみんなに共有できるようになる
・システムのスクラップ&ビルドが容易になる
などの嬉しい効果が生まれます。

これに限らず、APIを使って、データを入力すると結果を返してくれるような仕組みを作ってあげたりなんだりなど、やり方はありそうです(webアプリケーションの開発も容易にできるようになります)。

仰々しく見えますが、作るの自体にはあまり手間はかからないので、機会があればイメージアップの為にモノをお見せします。

**Comment by akikirinrin** [comment]
率直に言うとないっす。ぜひお願いします

**Comment by AnguillaJaponica** [comment]
米国(NOAA)・EU勢もこういうのはあまり盛んに(オープンにしてないだけかも...？)やってなさそうなので、面白そうかもですね。

**Comment by akikirinrin** [comment]
我々の組織では、どうしても飛び道具的に響いてしまうんです。お知恵を貸してください。
成果物の当たり前品質を保証し続けるためには必要不可欠なものであると、
ほぼ全員が納得した状況(短くいうと文化)を養っていく必要があると感じています。

「目指す姿を詰める」というのもかなり深みのある作業と思います。
DevOpsの円環は切れ目がないので、だからこそ我々にとって参入がとても難しいです。

ガラパゴスに種子を恵んで下さい。

**Comment by AnguillaJaponica** [comment]
いえいえ、そんな(汗

資源解析の知見や国内外の研究期間/研究者との繋がりその他目の付け所etcと、私の持っていないものをみなさま多く持っておられるので、私も学びたいところです。

さっき個人的にAWSに立てたサーバにsshで接続してRの計算をまわせるようにしたので、またお会いする機会に諸々お見せしますね(ちなみにIPアドレスさえ教えていただければ今からでも林さんアクセスできますよ)。
![image](https://user-images.githubusercontent.com/47109605/71713097-89f23c00-2e4b-11ea-88ce-56ddb1ebe08d.png)

**Comment by AnguillaJaponica** [comment]
https://github.com/ichimomo/frasyr/issues/179
と同様、クローズします。
