### ISSUE TITLE
check()でerror

### ISSUE THREAD

**Issue by ShotaNishijima** [ichimomo/frasyr#181]
check()をすると、
`Error in parse(text = x) : <text>:1:1: unexpected input`
というエラーが出て、チェックが通らない。どこの場所が原因かが分からない…

**Comment by ShotaNishijima** [comment]
福井さんも同様のエラーが出ることは確認済みです

**Comment by ShotaNishijima** [comment]
masterでも起こります

**Comment by AnguillaJaponica** [comment]
checkの処理は5,60くらいのチェックポイントを一つずつ追っていく処理をやっているので、関数の仕様を調べてどのへんでコケているのか調べてみるのが良いかなと思います。順番的に一番最初に行われるのはusing log directory(‘/Users/terumasataka/Documents/web/httr.Rcheck’みたいなの)の部分だったはずなので、まずはそこから洗ってみてはいかがでしょう？エラーログに「'」だけ表示されてるとかいう箇所はありませんか？

そこの記載にかかる文字コードの問題etcでうまくパースできず、エラーが出てしまうというバグな気がします。ググりながら対応してみてください。github上のやりとりだとやりづらいようでしたら、slackのワークスペース作るのでそちらで会話しながらバグフィックスしましょうか。

↓このへんが役立つかも。
http://r-pkgs.had.co.nz/check.html

**Comment by ichimomo** [comment]
たしかに私の環境（＠Lubuntu, emacs）ではエラーおきないです。
申し訳ありませんが、エラー起こる方の環境で、原因究明して頂ければ幸いです。

開発環境の統一は長期的な課題ですね。ご指摘、ありがとうございます。

**Comment by AnguillaJaponica** [comment]
少なくともichimomoさんの環境をDockerで再現して配布すれば良いと思うので、そこまで長期的にはかからないかなと思います。インフラがコード化される、良い世の中になりました。。

開発用だけじゃなく、研修用の環境を作って大勢に配るなんかもこれでできますね。

↓がわかりやすいかなと思います。またの機会にお話できれば。
https://uribo.hatenablog.com/entry/2017/12/21/212941

**Comment by AnguillaJaponica** [comment]
@ShotaNishijima 
取り急ぎ上記の対応に加えて、↓あたりを読みながら文字コードの設定を変えて実行してみてください。
(私の方からは環境が見えないので、完全解決まで行けるかはわかりませんが。。)

ダメならdockerなど別の手で行きましょう。check使わないまま(テストもですが)開発進めるとどこかで戻れなくなるので、早めに潰したいですね。

https://shohei-doi.github.io/notes/posts/2019-04-25-encoding-r/
https://kitamix.net/archives/default-text-encoding-with-r-studio/900

**Comment by ShotaNishijima** [comment]
Laptop (Windows10) だとerrorが出なかったので、OSの問題ではないようです。macでも出る人は出てますし。
`Writing NAMESPACE`
でerrorが出ているようなので、roxygen2のせいかなと思い、見てみたら僕のバージョンは7.0.2でfrasyrのDESCRIPTIONは6.1.1となっているので、そのせいかもと思いました。
バージョン落として合わせようかと思ったのですが、他のパッケージ (VASTなど) に問題を起こしそうなので止めておきます。とりあえず、いま大幅に変更する予定ないので…

**Comment by AnguillaJaponica** [comment]
確かにそこかもしれませんね。ありがとうございます。知見をいただけました。

**Comment by ichimomo** [comment]
市野川のほうでもcheckが通らなくなるエラーを確認できました．
VASTがインストールされている環境下で（Linuxでも），checkが通らなくなるようです．

**Comment by ichimomo** [comment]
原因はわかりませんが，この3行をコメントアウトすると，checkが通るようになりました．
https://github.com/ichimomo/frasyr/blob/630166afdf21ac00d6cb9463465ada2fe46399bf/R/utilities.r#L1413-L1415
次回，devを更新するタイミングでとりあえずコメントアウトしておきます．

**Comment by ichimomo** [comment]
すみません、ラベルを付けたり外したりして混乱させてしまいましたが、、、。

#202 の更新で、自分の環境ではテストも全部クリアしてcheckも正常に終了したんですが、travisのほうのbuildでエラーが出ます。なんで出ているか誰かわかりますでしょうか？

**Comment by ichimomo** [comment]
とりあえず、ルートディレクトリとtestディレクトリにあった不要ファイルを削除して様子を見ています

**Comment by ichimomo** [comment]
やっぱりだめでした。。。

**Comment by ichimomo** [comment]
devtools::build()で試さないといけないんですね。buildすると、vignetteの作成でつまづいていることがわかりました。

**Comment by AnguillaJaponica** [comment]
テストの書きかえお疲れ様でした(バトンタッチしたんですね。ものすごい分量...流石です。。)。

このissueに限らないんですが、エラーログも一緒に残していただけますか？どこの処理でつまづいているかわかって、他の方もレビューしやすくなります。

このエラーログをプルリクなどにコピペしておくのももちろん良いのですが、slackに結果を自動通知するように設定しておくと、逐一ページを開いて行を追って...ということをしないで済みます。3回同じ作業をやったら、その作業自体を滅するか自動化するかを検討すると良いです。

https://qiita.com/nwtgck/items/17840855cb76f60fa1fe
↑などにしたがって設定をかけてみてください。林さん・木下さん・真鍋さんのどなたかに相談すればなんとかしてくださるはずです。

**Comment by AnguillaJaponica** [comment]
本当は私も同じslackのワークスペースに入ってレビューや運用面見られればいいんですが、FRAの組織規程的に今の私の立場だとできなそうですね(本当は今やってるこのレビューもグレーなのかなとお察ししています)

**Comment by ichimomo** [comment]
- vignetteのbuildに失敗していました。vignette内で呼び出しているtidyverseがDESCRIPTIONに記載されていなかったあたりが問題だったのかなと思います。ただ、DESCRIPTIONにはtidyverseでなく個々のパッケージを記載したほうが良いとどこかで聞いたような気がして、バラバラにパッケージを指定していたんですが、でも、スクリプト上ではlibrary(tidyverse)で呼び出すほうが簡潔だし、、ということで、とりあえず、問題となったvignetteを退避しました
