### ISSUE TITLE
future_tmb.r 449行目について

### ISSUE THREAD

**Issue by YodaMari** [ichimomo/frasyr#188]
dev版を使用して、
demo_MSE　についてマアジ対馬暖流系群のデータで計算を行ってみています。

future_tmb.r　の449行目で

"M" を "M_mat" に修正する必要があるのではないでしょうか。

popeの近似式を使っているマイワシ対馬ではエラーが出なかったのですが、
サバやアジではエラーが出ており、該当箇所を修正するとその次に進むことができました。

**Comment by ichimomo** [comment]
ご連絡ありがとうございます。対応してdevにアップしました。
