### ISSUE TITLE
fit.SRregimeの出力

### ISSUE THREAD

**Issue by ichimomo** [ichimomo/frasyr#192]
引数で与えるregime.keyの番号と，出力のregime番号が一致していないので，一致するような出力をしてほしいです（regime番号をずらすか，新たにregime.keyに対応するような出力をするか）

よろしくお願いします．

**Comment by ShotaNishijima** [comment]
#195 で対応したのでクローーズします

**Comment by ichimomo** [comment]
すみません，修正した関数を使ってみましたが，regime_predのところのラベルが以前のままでした．そちらも修正いただけたら幸いです．
