### ISSUE TITLE
allresults.csvのperSPRの数値が高いようだ

### ISSUE THREAD

**Issue by symuko** [ichimomo/frasyr#247]
allresults.csvの#MSY Reference pointsに記載されているperSPR、数値が全般的に高いように思います。

MSYのときにperSPR=0.545です。Fref/Fcur=1.012でほぼ変わらず、エクセルVPAではFcurの%SPRは40.48％という結果を得ています。

計算の条件などを教えていただけないでしょうか。

**Comment by ichimomo** [comment]
管理基準値計算のために実施した将来予測の最終年の生物パラメータを使っているようです
https://github.com/ichimomo/frasyr/blob/6dece4441c60400a02b29c4d5a62ff47f569fdef/R/utilities.r#L1337-L1371
仮定している生物パラメータがちがっていないでしょうか？

**Comment by symuko** [comment]
将来予測のパラメータは、指定年通りを確認しました。
#YPR＆SPR historyの結果から類推すると、perSPRにはSPRの値が入っているように思うのですが、いかがでしょうか？

**Comment by ichimomo** [comment]
すみません、どことどこの数字を見比べて違っていると考えているのか、もう少し具体的に教えていただけないでしょうか？バグだとしたら急いで修正しないといけないので

**Comment by symuko** [comment]
将来予測のパラメータは、指定年通りを確認しました。
また、allresults.csv の# YPR & SPR history にある過去のperSPRは、エクセル計算と一致しています。将来予測に関しての計算部分のようです。

**Comment by ichimomo** [comment]
上記の修正で、緊急的に、全部の生物パラメータが0となっている年齢については考慮しない、というコードを挿入しました。ただ、実際的には、どの年齢をプラスグループと考えるかの明示的に指定するようなやり方に変更が必要です。今後、おちついたら修正します。
また、これに付随して #248 の問題も気づきましたが、当面は使っていないため保留します。

**Comment by symuko** [comment]
ありがとうございます。計算してみます。
＋グループにNAが入っているための問題ということでしたが、年齢構成に変更がない他魚種への影響はないでしょうか。

**Comment by ichimomo** [comment]
多分大丈夫だと思うのですが，現状，％ＳＰＲの計算，いろんな関数を使ってやっているので，ちょっと（かなり）混乱している部分があります．令和元年度の会議では，みなエクセルで計算をたしかめてくれていたので大丈夫だと思うのですが，令和2年度のほうではみな確認してくれているかわかりません．エクセルで確認できる内容だとおもうので，余裕のある人みてみていただけたら幸いです．（一つ一つの関数の挙動についてはいちおうテストしていますが，引数の与え方とか，参照年を間違っているとか，プラスグループの仮定とかについて，各魚種で想定されている設定と違うかもです）

**Comment by symuko** [comment]
％SPR、一致しました。
修正、ありがとうございました。早くに確認しておけばよかったです…。
