### ISSUE TITLE
sd.predの変更

### ISSUE THREAD

**Issue by ichimomo** [ichimomo/frasyr#260]
https://github.com/ichimomo/frasyr/pull/257
こちらでL1の場合のsdの出力を変えたと思うのですが、その場合テストが通らなくなるはずではないでしょうか？私も時間あったら対応しますが、もしすぐわかる方いらっしゃいましたら、教えてください（今日中に2.01をアップするというスケジュールのため）

**Comment by ichimomo** [comment]
ぱっと見た感じ、fit.SRの出力結果を網羅的に比較するような構造になってないですね、、fit.SRの出力をfuture.vpaに食わせてその結果が一致するかをテストしているので、、

また、fit.SRの結果をfuture.vpaに食わせる部分で、
https://github.com/ichimomo/frasyr/blob/0c379f15b20e3f22a4835f06ab3ff7ec0eadaad9/tests/testthat/test-future-part.R#L83-L108
となってますが、fres_pma_recarg_listには保存されたパラメータから読み込んだものを使っているため、結果としてfuture.vpaのテストはできていますが、fit.SRのテストにはなっていません

福井さん案件かと思いますが、問題共有のため、西嶋さんもいちおうまだアサインさせてください

**Comment by ichimomo** [comment]
すみません、fit.SRの結果をテストするためのファイルは別のところにあるby福井さんとのことです。となると、やっぱりｓｄの値が違ってもテストが通るのはちょっとおかしいので、引き続き福井さんにご検討いただきます

**Comment by ichimomo** [comment]
確認したところ、テストではちゃんと過去のSDの出力と、新しい変更後のSDの出力を比較する部分がありました。そして、修正後のコードはここを通過している＝SDが置き換わっていない、ようです。西嶋様、（休み明けで大丈夫なので）ご確認いただけないでしょうか？更新版のアップは明日にしたいと思います。

**Comment by ShotaNishijima** [comment]
SD自体は置き換わっているように見えます。L1だけ変わればいいんですよね？
> resHSL1 = fit.SR(SRdata, SR = "HS", method = "L1", out.AR = FALSE, AR = 0, rep.opt = TRUE)
> resHSL1$pars
           a       b        sd rho
1 0.03093773 2775634 0.7904917   0
> resHSL1$sd.pred
[1] 0.8492677

再テストしてみましたが、errorは起こりませんでした。
`== Results =====================================================================
Duration: 280.2 s

OK:       743
Failed:   0
Warnings: 6
Skipped:  0`

`devtools::test("~/git/frasyr")` でOKですよね？
テストコードのどの部分でしょうか？
Skipされてしまうなんてことないですよね？

**Comment by ShotaNishijima** [comment]
> resHSL1 = fit.SR(SRdata, SR = "HS", method = "L1", out.AR = FALSE, AR = 0, rep.opt = TRUE)
> resHSL1$pars
           a       b        sd rho
1 0.03093773 2775634 0.7904917   0
> resHSL1$sd.pred
[1] 0.8492677
> sqrt(sum(resHSL1$resid^2/length(resHSL1$resid)))
[1] 0.7904917

pars$sdはRMSEと一致するようになっていますが、そちらではなっていませんか？

**Comment by ichimomo** [comment]
こちらでも簡単なテストコードを作って走らせると、確かにmaster版とdev版で、res_L1$pars$sdの値は変わっていました。そして、dev版のresHSL1$pars$sdは sd(resHSL1$resid)と一致しました。ので、コードは正しいと思います。

SRdata <- list(year=2000:2019,SSB=c(rep(1:5,2),3),R=1*exp(c(rep(-1,4),-2,rep(1,4),2,0)))
res_L2 <- fit.SR(SRdata,method="L2",AR=0) 
res_L2$pars
res_L1 <- fit.SR(SRdata,method="L1",AR=0) 
res_L1$pars
plot_SRdata(SRdata)
points(res_L1$pred,type="l")
points(res_L2$pred,type="l",col=2)  

やはりテストの問題？

**Comment by ichimomo** [comment]
ちなみに、上のテストの結果は、master版で

> res_L1$pars
          a        b       sd rho
1 0.9999992 1.000001 1.542778   0

dev版で
> res_L1$pars
          a        b       sd rho
1 0.9999992 1.000001 1.206045   0

となります。期待通りの挙動にはなっています。

**Comment by fshin3** [comment]
test code の間違いでした。すみません。
testcontents[i] の照合で for( i in 1:length(testcontens)) が　for(i in length(testcontents))になってました。

**Comment by ichimomo** [comment]
修正版をマージしました。それだとテストが通らなくなると思いますが、それはこちらで暫定的に修正します。

**Comment by ichimomo** [comment]
https://github.com/ichimomo/frasyr/blob/65cf22bd0199f58ddcb6481173a293d712331628/tests/testthat/test-stock-retruit-part.R#L28-L34

test-stock-recruit-part.Rに上のようなコードを追加しました。新しいコードのｓｄはsqrt(mean((resid)^2))と一致して、新しいコードのsd.predは古いコードのsdと一致するという内容です。これをテストすると以下のようになりまして、ARを内部推定するときの古い関数によるsdの出力値と、新しい関数のsd.predがずれるようです（下3つのエラー）。（上2つのエラーは少数点0.001以下なのでまあいいかなと。torelanceは0.001でつけているんですが）

こういうもんですか？そもそもARあり＆L1というのは推奨されないので、もうテストから外して保証範囲外としますか？

test-stock-retruit-part.R:31: failure: oututput value check
SR.list[[i]]$pars$sd not equal to sqrt(mean((SR.list[[i]]$resid)^2)).
1/1 mismatches
[1] 0.264 - 0.265 == -0.00122

test-stock-retruit-part.R:31: failure: oututput value check
SR.list[[i]]$pars$sd not equal to sqrt(mean((SR.list[[i]]$resid)^2)).
1/1 mismatches
[1] 0.264 - 0.266 == -0.00212

test-stock-retruit-part.R:60: failure: oututput value check
eval(parse(text = paste("SRpma_HS_L1_AR1_outAR0$", testcontents[i]))) not equal to eval(parse(text = paste("SRpma_HS_L1_AR1_outAR0_check$", testcontents[i]))).
Component "sd": Mean relative difference: 0.08248023

test-stock-retruit-part.R:107: failure: oututput value check
eval(parse(text = paste("SRpma_BH_L1_AR1_outAR0$", testcontents[i]))) not equal to eval(parse(text = paste("SRpma_BH_L1_AR1_outAR0_check$", testcontents[i]))).
Component "sd": Mean relative difference: 0.03691361

test-stock-retruit-part.R:154: failure: oututput value check
eval(parse(text = paste("SRpma_RI_L1_AR1_outAR0$", testcontents[i]))) not equal to eval(parse(text = paste("SRpma_RI_L1_AR1_outAR0_check$", testcontents[i]))).
Component "sd": Mean relative difference: 0.03526284

**Comment by ichimomo** [comment]
ちなみに、さっき変更したファイルには

https://github.com/ichimomo/frasyr/blob/65cf22bd0199f58ddcb6481173a293d712331628/tests/testthat/test-stock-retruit-part.R#L191-L209

というようなテストも追加しています。本来ならこのような形で正解のわかっているデータでテストするのが必要なので今後の課題です（このテストは現状通っています）。（ただ、ARありのばあいが難しいです）

**Comment by ShotaNishijima** [comment]
どうもありがとうございます。単に結果が一致するというだけでなく、そういったテストも必要だろうと思っていたので助かります。自己相関がある場合は、ar関数やarima関数といったすでにある関数と結果を一致するのがいいのではないかと思います。
L1＆ARありの場合は過去のsdとsd.predは一致しないと思います。結局ar関数を使って事後推定のようなことをしてそれをsdに入れていたので。
気になるのは最初の2つで、なんで微妙にずれるんでしょう…？

**Comment by ichimomo** [comment]
L1&ARについては過去のSDと合わないこと、了解です。とりあえずテストの対象から外します。
こんなかんじで
https://github.com/ichimomo/frasyr/blob/57dedbae6cfc603491554b4e3ef71622edef43e0/tests/testthat/test-stock-retruit-part.R#L62-L65

また、最初の2つ（SR.list[[i]]$pars$sd not equal to sqrt(mean((SR.list[[i]]$resid)^2))）については、じつは合わないのは二つだけでなくてtorelanceを設定しないと、L1かつARありの5つについて一致しません。↓のようなかんじです。4 not equal to... の4という数字が網羅的にやるときの行番号です。とくに11～12の自己相関ありでρ内側推定の場合で差が大きいですね。

test-stock-retruit-part.R:31: failure: oututput value check
4 not equal to sqrt(mean((SR.list[[i]]$resid)^2)).
1/1 mismatches
[1] 0.259 - 0.259 == -0.000156

test-stock-retruit-part.R:31: failure: oututput value check
5 not equal to sqrt(mean((SR.list[[i]]$resid)^2)).
1/1 mismatches
[1] 0.263 - 0.263 == -0.00022

test-stock-retruit-part.R:31: failure: oututput value check
6 not equal to sqrt(mean((SR.list[[i]]$resid)^2)).
1/1 mismatches
[1] 0.263 - 0.263 == -0.000322

test-stock-retruit-part.R:31: failure: oututput value check
10 not equal to sqrt(mean((SR.list[[i]]$resid)^2)).
1/1 mismatches
[1] 0.259 - 0.26 == -0.000571

test-stock-retruit-part.R:31: failure: oututput value check
11 not equal to sqrt(mean((SR.list[[i]]$resid)^2)).
1/1 mismatches
[1] 0.264 - 0.265 == -0.00122

test-stock-retruit-part.R:31: failure: oututput value check
12 not equal to sqrt(mean((SR.list[[i]]$resid)^2)).
1/1 mismatches
[1] 0.264 - 0.266 == -0.00212

ということで、L1かつARありについてはもともと動作保証範囲外として、torelanceを思いっきり下げました。一方、L1ARなしについては、torelanceを設定しなくてもテストは通ります。
https://github.com/ichimomo/frasyr/blob/57dedbae6cfc603491554b4e3ef71622edef43e0/tests/testthat/test-stock-retruit-part.R#L32-L33

以上の変更でいちおうテストは通るようになりました。

今後、再生産関係のテストについては要修正ということで、このissueは閉じないでおいておきましょうか、、

**Comment by ShotaNishijima** [comment]
ARありのときのsd.predには何を入れるか話し合いましたっけ？僕は自己相関を推定した際に説明できなかった残差のSDを入れていました。なので、residは自己相関を除いたものなので、結果が一致しないのは当然かと…。テストデータはrhoが小さかったので、割と一致していますが…

**Comment by ichimomo** [comment]
> ARありのときのsd.predには何を入れるか話し合いましたっけ？僕は自己相関を推定した際に説明できなかった残差のSDを入れていました。

ARありのときに何が入っているのか、、、全然わからないまま、作業していました（一致しないはず、というお言葉をたよりに）。テスト追加・修正してくださってありがとうございます。

本来なら、正解がわかっているデータでテストが通ればそれで良いので、過去の結果の再現できるかどうかテストは、新しいテストコードでカバーできるようになったら順次消していくのが良いと思います。将来予測のほうのテストコードも、今はもう使っていないfuture.vpaのテストを一所懸命やっていて時間とられていて、最新のfutute_vpaのテストは最小限（）にとどまってますし、、。将来予測のほうのテストは私のほうで時間が空き次第見ていきたいと思います。
