### ISSUE TITLE
travisにテストのカバー率を測る設定を追加する

### ISSUE THREAD

**Issue by ichimomo** [ichimomo/frasyr#276]
travisにテストのカバー率を測る設定を追加する

_Originally posted by @ichimomo in https://github.com/ichimomo/frasyr/issues/271#issuecomment-622211308_

## 追加で取り組むタスク
- [x] 不要な設定を削除

**Comment by ichimomo** [comment]
codecovのテストの細かい結果を見るところ、例えば↓ってみんな見れますか？私のアカウントからしか見れないですか？
https://codecov.io/gh/ichimomo/frasyr/src/f498e1d84445694fdd950b211b7df28c6d46068e/R/future.r

**Comment by akikirinrin** [comment]
見れましたよー :+1:
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/14845847/80897654-05022b00-8d36-11ea-8a8f-7131b239f6fd.png">

**Comment by Rindrics** [comment]
Done
