### ISSUE TITLE
.Rprojで設定を統一する

### ISSUE THREAD

**Issue by akikirinrin** [ichimomo/frasyr#291]
Windowsで改行コードがCRLFになったりする。

gitの方の設定は
`git config --global core.autocrlf input`
でしてもらうとして

Rstudioの改行コードも強制LFにしておいたほうがいい。

**Comment by akikirinrin** [comment]
.Rprojのリネームも必要

**Comment by ichimomo** [comment]
こういうissueはどんどんcloseしていっても良いんですよね？　もし終わっているようでしたらcloseしていただければ、、。

**Comment by akikirinrin** [comment]
すいません、ありがとうございます！https://github.com/akikirinrin/frasyr/commit/1c0d1ad41028761a51de31edbdfee4b76190a092 がされた時点ではデフォルトのmasterにマージされてないので、実際は解決されていない状態ですね。
