### ISSUE TITLE
stock_recruit.R周りのテストをリファクタリング

### ISSUE THREAD

**Issue by Rindrics** [ichimomo/frasyr#294]
https://github.com/ichimomo/frasyr_tool/issues/92
に関連して、fit.SR()の使い方を個人的に復習するしないと、タスクを作れないことに気づきました。
https://github.com/ichimomo/frasyr/blob/f2f9a9a9d8666cc0ecbcc4ba73edbbad942ffab5/tests/testthat/test-stock-retruit-part.R#L18 あたりを使って練習するついでに、リファクタリングします

**Comment by akikirinrin** [comment]
devが壊れてるので `f54149b *   Merge pull request #285 from ichimomo/update_test`からやります

**Comment by akikirinrin** [comment]
よくみたらもともとの https://github.com/ichimomo/frasyr_tool/issues がアサインされてなかったのでおります。手もとの作業はstashしておきます

**Comment by Rindrics** [comment]
stashed
