### ISSUE TITLE
est.MSYのエラー

### ISSUE THREAD

**Issue by ShotaNishijima** [ichimomo/frasyr#31]
future.vpaでwaa.year=NULL, maa.year=NULLで代わりにwaaとmaaを指定してest.MSYを計算すると以下のエラーが出ます。たぶん世代時間を計算している関数が、waa.year / maa.yearで計算しているからなのかなと思いました。

Error in seq.default(from = start.year, to = start.year + nyear + add.year,  : 
  'to' must be a finite number
In addition: Warning messages:
1: In max(age) : no non-missing arguments to max; returning -Inf
2: In age * L :
  longer object length is not a multiple of shorter object length
3: In age * L * maa :
  longer object length is not a multiple of shorter object length
4: In L * maa :
  longer object length is not a multiple of shorter object length

**Comment by ichimomo** [comment]
ご報告ありがとうございます．
Generation.Time関数の実行は，GTを具体的に与えたら回避できるので，
とりあずは外部から引数GTを与えてGeneration.Time関数の実行を回避するしかないと
思いますが，将来的にはこのような不具合がおきないように修正しないといけないですね．

ただ，どう直すか，
waa, maaを明示的に与えるような状況っていうのは，将来の年代によってこれらのパラメータが変化させたいという状況だと思いますが，一方でGeneration.Timeは一つの値を返す値なので，
ちょっと難しい感じです．
自動的に平均のパラメータをとるようにしても良いけど，ブラックボックス化するのも良くない
ので，「外からＧＴを与えてください」というエラーを吐いて実行を停止するようにしたほうが
良いのか．．．

ちょっと考えてみます．

**Comment by ichimomo** [comment]
frasyr_toolを使ったこのあたりのコントロールはfrasyrの外側からおこなうことにしたので，いったんcloseします
