### ISSUE TITLE
abund.extractorのテスト

### ISSUE THREAD

**Issue by mmitsuyo** [ichimomo/frasyr#312]
今あるテストに加えて，さらに網羅的なテストを追加する（答えが分かっているようなダミーデータで）

**Comment by ichimomo** [comment]
このあたり、abundのオプションの与え方によってたくさんの分岐ができていますが、すべての分岐がテストで網羅されていないということころがちょっと気になったところです。
https://github.com/ichimomo/frasyr/blob/b598d21b7c526a05a0f96795261b181df85fc8fa/R/rvpa.r#L231-L261
"Bs", "Bo","SSBm"とか、コード中に説明がないオプションもコードがあったり、、。これら、それぞれの系群の様々な要望にあわせて追加されていったオプションだとは思いますが、いちおう、これらオプションが全部予想通りに動いているのか、いちどテストしたほうがよいのかなと。
ここがVPA関数の肝で、この内部を拡張することによって、いろんなチューニングができるようになると理解しているので、大事な個所だと思います。

**Comment by mmitsuyo** [comment]
コメントありがとうございます．承知しました．たしかにここらへんのテストも重要ですね．なるべく早く対応します．
