### ISSUE TITLE
VPAのヘルプの充実化

### ISSUE THREAD

**Issue by mmitsuyo** [ichimomo/frasyr#313]
VPAのチューニングオプションに関するHelpをより充実化する

**Comment by ichimomo** [comment]
https://github.com/ichimomo/frasyr/issues/575
このへんで一部対応したと思いますが、closeしてしまっていいですか？

**Comment by YuuhoYamashita** [comment]
helpの加筆、どうもありがとうございました！
ところで今頃すみません、vpa()の引数で
選択率関係（sel.defなど）の指定についての説明なども追加していただけませんでしょか？

選択率更新法で、2019年の選択率を2016-2018年のFの平均値の選択率（2016-2018年の選択率の平均値ではなく）として計算したいのですが、この場合の指定方法がよく判りませんでした。
今頃すみませんが、どうぞよろしくお願いいたします。

**Comment by mmitsuyo** [comment]
承知致しました．明日朝一で対応致します．少しお待ちください．
