### ISSUE TITLE
retrieve_input()を作る

### ISSUE THREAD

**Issue by Rindrics** [ichimomo/frasyr#317]
科学者会議の設定を再利用したい

https://github.com/ichimomo/frasyr_tool/pull/133#issuecomment-641016372

**Comment by akikirinrin** [comment]
https://github.com/ichimomo/frasyr_tool/issues/138 より、`new_sd`オプションが必要

**Comment by akikirinrin** [comment]
typoでビルド壊しちゃってたので直しました
