### ISSUE TITLE
sigma.const? sigma.constraint?

### ISSUE THREAD

**Issue by ShotaNishijima** [ichimomo/frasyr#325]
`vpa()`で、`sigma.const`と`sigma.constraint`という似たような種類の引数が2つあるんですが、何が違うのでしょうか？どう使えばいいのですか？

**Comment by mmitsuyo** [comment]
https://github.com/ichimomo/frasyr/pull/343
一応，上記サイトで議論して，修正致しました．
ご確認のほど宜しくお願い致します．

**Comment by ShotaNishijima** [comment]
確認できました。ご対応どうもありがとうございました。
