### ISSUE TITLE
ｂの値も出力

### ISSUE THREAD

**Issue by ichimomo** [ichimomo/frasyr#334]
こちらもよろしくおねがいします

https://github.com/ichimomo/frasyr/blob/5efb6d06e58d806bf8a354fd8beed9764d7a7c49/vignettes/Diagnostics-for-VPA.Rmd#L353-L355

**Comment by KoheiHAMABE** [comment]
bの値もreturnに加えておきました
やっぱり、map関数のの方がすっきりしますね
