### ISSUE TITLE
最小二乗法の場合のレトロ

### ISSUE THREAD

**Issue by ichimomo** [ichimomo/frasyr#335]
https://github.com/ichimomo/frasyr/blob/5efb6d06e58d806bf8a354fd8beed9764d7a7c49/vignettes/Diagnostics-for-VPA.Rmd#L376

**Comment by KoheiHAMABE** [comment]
関数内で推定法について指定していないので、今の`do_retrospective_vpa`関数では最小二乗法の結果を与えれば、最小二乗法でレトロできています
同様に、ジャックナイフ、ブートストラップ法なども最小二乗法対応しています
