### ISSUE TITLE
vpa関数に残差プロットを入れ込む

### ISSUE THREAD

**Issue by ichimomo** [ichimomo/frasyr#338]
残差プロットの関数がだいたいできてきたら，vpa関数の実施時に自動的に出力される残差プロット
https://github.com/ichimomo/frasyr/blob/5efb6d06e58d806bf8a354fd8beed9764d7a7c49/R/rvpa.r#L1273-L1279
を，新しい残差プロット関数を使ったものに置き換えていただけるでしょうか？

ただ，新しい関数はまだバグが怖いので（たぶんだいじょうぶだとおもいますが）
こんなかんじで↓，新しい関数をtry()関数に入れてください．これを使うと，tryの中身が評価されてエラーが出ても関数の実行が止まらずに先に進みます．そのさい返り値（graph）にはclass(graph)が"try-error"であるオブジェクトが入ります．なので，次の行でgraphのclassが"try-error"に一致していたら，plot_residual_vpaは失敗してしまったということなので，従来通りの残差プロットをする，という形に切り替えられると思います．

```
graph <- try(plot_residual_vpa(res, index_name = NULL, plot_scale = FALSE, plot.year=XXX )) # plot.yearに対応する引数を追加してください
if(class(graph)=="try-error"){
    以前のplotの記述
}
else{
  gridExtra::grid.arrange(graph$year_resid, graph$fitting_CPUE,graph$abund_CPUE) # 3つのggplotを並べる
}
```

gridExtraは複数のggplotを並べるためのライブラリです．今までfrasyrでは必須のパッケージとして登録してなかったですが，この機会に登録しました　↓
https://github.com/ichimomo/frasyr/commit/3709a31de6cc00e8c9a48a36add8e576adeae0a9#diff-35ba4a2677442e210c23a00a5601aba3

**Comment by KoheiHAMABE** [comment]
plot_residual_vpa関数の引数がvpa関数の結果のオブジェクトを与えるようにしているので、関数の方の手直しが必要かもです

**Comment by KoheiHAMABE** [comment]
直前にresってオブジェクトあるので問題ないかと思います。二転三転してすみません
https://github.com/ichimomo/frasyr/blob/5efb6d06e58d806bf8a354fd8beed9764d7a7c49/R/rvpa.r#L1271

**Comment by symuko** [comment]
vpa(, plot=TRUE)では以下のエラーがでて動きませんでした。

`geom_smooth()` using method = 'loess' and formula 'y ~ x'
 gList(list(grobs = list(list(x = 0.5, y = 0.5, width = 1, height = 1,  でエラー: 
  only 'grobs' allowed in "gList"
 追加情報:  警告メッセージ: 
1: Removed 184 rows containing non-finite values (stat_smooth). 
2: Removed 184 rows containing missing values (geom_point). 

vpa(, plot=FALSE)は結果が帰ってきます。
その後、plot_residua_vpa（）を動かすと
$year_resid, $abund_Index, $fitting_Index → 出力
$fitting_CPUE, $abund_CPUE → NULL
となります。

**Comment by symuko** [comment]
$abund_Index,$fitting_Index ですが、チューニング期間の資源量と、過去の資源量が違いすぎるため、
Y軸メモリが大きくなりすぎてしまいます。

各Indexごとに、適当な範囲にY軸を指定したいのですが、可能でしょうか？
引数plot_scaleかな？と思ったのですが、function(plot_residual_vpa)には指定がないように見えました。

**Comment by KoheiHAMABE** [comment]
> 
> 
> vpa(, plot=TRUE)では以下のエラーがでて動きませんでした。
> 
> `geom_smooth()` using method = 'loess' and formula 'y ~ x'
> gList(list(grobs = list(list(x = 0.5, y = 0.5, width = 1, height = 1, でエラー:
> only 'grobs' allowed in "gList"
> 追加情報: 警告メッセージ:
> 1: Removed 184 rows containing non-finite values (stat_smooth).
> 2: Removed 184 rows containing missing values (geom_point).
> 
> vpa(, plot=FALSE)は結果が帰ってきます。
> その後、plot_residua_vpa（）を動かすと
> $year_resid, $abund_Index, $fitting_Index → 出力
> $fitting_CPUE, $abund_CPUE → NULL
> となります。


issueありがとうございます。
vpa(, plot =T)ですが、現在関数の修正を行いましたので、再度frasyrのdevブランチをインストールして頂ければ（以下コード）、作図できるかと思います。

`devtools::install_github("ichimomo/frasyr", ref="dev")`

ご不便おかけしてしまい、すみませんでした。
他のissueについても、急ぎ対応させて頂きますので、少々お待ちください。

**Comment by symuko** [comment]
早速のご対応、ありがとうございました。素早いレスポンスで大変ありがたいです。
vpa(, plot=T)で、３種類の残差プロットが出ることを確認しました。

なお、plot_residua_vpa()の$fitting_CPUE, $abund_CPUEはNULLのままでした。
どうぞよろしくお願いいたいsます。

**Comment by KoheiHAMABE** [comment]
plot_residual_vpa関数の結果は

- $fitting_Index
- $abund_Index

でプロットできます。
もしかすると配布したスクリプトと、出力名が変わっているかもなのでお気を付けください
以下、GitHubで見れるスクリプトです。こちらベースに参考にして頂けると幸いです。
https://ichimomo.github.io/frasyr/articles/Diagnostics-for-VPA.html

**Comment by symuko** [comment]
ありがとうございます。
スクリプトの説明で、大きく3種類のプロットと紹介している導入部が
$fitting_CPUE, $abund_CPUEになっていました。

$fitting_Index, $abund_Indexのことならば、ご変更をお願いいたします。

**Comment by KoheiHAMABE** [comment]
ご指摘ありがとうございます。今こちらで修正しております。
ご不便おかけしておりますが、少々お待ちください。

**Comment by KoheiHAMABE** [comment]
> $fitting_Index, $abund_Indexのことならば、ご変更をお願いいたします。

ご不便おかけして申し訳ありません。
スクリプトの方も変更してあります。
引き続き、よろしくお願いします。

**Comment by KoheiHAMABE** [comment]
こちらも順調に動いているので、closeします
