### ISSUE TITLE
チューニングVPAの2段階法に対応してほしい

### ISSUE THREAD

**Issue by akimanabe** [ichimomo/frasyr#374]
# tVPA 2 step
[市野川＆岡村(2014)](http://www.jsfo.jp/contents/pdf/78-2/78-2-104.pdf)より抜粋
- 最終年の漁獲選択率を仮定する
  - （多くの場合）先に資源量指数を用いない通常のVPAを行う
  -  推定された最終年または特定年の漁獲選択率を仮定として用いることが多
い
- CPUEなどの資源量指数をデータに加え，資源量指数が最もよく説明できるような最終年・最高年齢の漁獲係数を推定する

**Comment by akimanabe** [comment]
☝️ 以下の機能を追加してほしいという話がABCWG会議で出たため

**Comment by ichimomo** [comment]
issueありがとうございます。
現状ではvpa関数を2回実施することで普通に2段階法は実行できるようになっています。問題になるのはデータを削りながら計算するレトロスペクティブ解析くらいでしょうか？ちょっとコーディングが複雑になりそうですが、相談して、今回のものに間に合うかどうか検討させていただきたいと思います。

**Comment by KoheiHAMABE** [comment]
西嶋さん作ってくださったのでclose
