### ISSUE TITLE
$abund_Index,$fitting_Index ですが、チューニング期間の資源量と、過去の資源量が違いすぎるため、

### ISSUE THREAD

**Issue by KoheiHAMABE** [ichimomo/frasyr#379]
$abund_Index,$fitting_Index ですが、チューニング期間の資源量と、過去の資源量が違いすぎるため、
Y軸メモリが大きくなりすぎてしまいます。

各Indexごとに、適当な範囲にY軸を指定したいのですが、可能でしょうか？
引数plot_scaleかな？と思ったのですが、function(plot_residual_vpa)には指定がないように見えました。

_Originally posted by @symuko in https://github.com/ichimomo/frasyr/issues/338#issuecomment-650873915_

**Comment by KoheiHAMABE** [comment]
関数の変更となると、修正に時間がかかりかつバグも発生するかもしれませんので、以下のように対応いただけますと幸いです。

- $abund_Indexについて
```
res <- plot_residual_vpa(XXX)
res$abund_Index + xlim(0, NN)

```
NNの箇所に、最近の資源量を入れて頂けると、併せてy軸目盛も小さくなるかと思います

- $fitting_Indexについて
```
res <- plot_residual_vpa(XXX, plot_year = 20XX:20YY)

```
とplot_year引数でプロットしたい期間を指定して頂けると、y軸の問題は消えるかと思います。

以上、よろしくお願いします。
また、不明点等ありましたら、お気軽にご連絡ください。

**Comment by KoheiHAMABE** [comment]
モデル診断関数の作図はggplot2というパッケージで行われています。
ですので、結果のオブジェクト（`res$abund_Index`のようなもの）に
`+ xlim(XX,YY) + ylim(XX,YY)`とすると作図範囲を手動で調整できます。(XXとYYには下限上限を与えてください)

ただし、$fitting_Indexのように各図のy軸のスケールがバラバラの場合は、後から手動で調整できませんのでお気を付けください。

**Comment by symuko** [comment]
ありがとうございます。
ylimで指定したら全部変わっちゃっので、ちょっとダメだなーと思って相談させてもらいました。
ggplot、自動化してくれる分不便なところがありますね。

$fitting_indexは、plot_yearの調整だけでは変わらないので、最大y値が使われているのだと思います。
$abund_indexはx軸の調整でうまく拡大できました！

**Comment by KoheiHAMABE** [comment]
$fitting_Indexの件ですが、お手数ですが以下のようにコードをご自身で書いて頂けると、恐らく過去の値にとらわれずにプロットできるかと思います。

```
res <- plot_residual_vpa(VPAres)
gg_data2 <- res$gg_data[res$gg_data$year == 20XX:20YY,]
g2 <- ggplot(gg_data2) +
  geom_point(aes(x=year, y=obs, colour = Index_Label), size = 2) +
  geom_line(aes(x=year, y=pred, colour = Index_Label), size = 1) +
  facet_wrap(~Index_Label, scale="free") +
  xlim(20XX,20YY) + ylim(0, NA) +
  ylab("Abundance index") +
  xlab("Year") +
  theme_SH(base_size = 14)
```

2行目のgg_data2というのがプロットしたい年度のみ抽出したデータになります。
2,7行目のXXとYYには適宜、プロットしたい範囲の年を書いて下さい。

よろしくお願いします。

**Comment by symuko** [comment]
ありがとうございます。
gg_data2 <- res$gg_data[res$gg_data$year == 2004:2019,]だと

 警告メッセージ: 
 res.tmi.resid$gg_data$year == 2004:2005 で: 
   長いオブジェクトの長さが短いオブジェクトの長さの倍数になっていません 

となり、データをうまく抽出できませんでした。対処療法ですが
gg_data2 <- res$gg_data[res$gg_data$year>= 2004,]にすると

データを抜き出し、scale=freeで書くことができました。

**Comment by KoheiHAMABE** [comment]
良かったです。

データの抽出はご指摘の通り
gg_data2 <- res$gg_data[res$gg_data$year>= 2004,]
としないと出来なかったですね。すみませんでした。
