### ISSUE TITLE
get.stat3のU.mean等について

### ISSUE THREAD

**Issue by ShotaNishijima** [ichimomo/frasyr#38]
get.stat3をいじっていて気になってのですが、漁獲割合の平均とかを
a$U.mean <- a$catch.mean/a$biom.mean
としていますが、正確には
U.mean <- mean(catch/biom)
ではないでしょうか？
それとも、平均同士の関係が一致するように便宜上こう定義しているということですか？

**Comment by ichimomo** [comment]
> 平均同士の関係が一致するように便宜上こう定義しているということですか？
そうです。MSYを達成するときの漁獲量（＝ＭＳＹ）と、ＭＳＹを達成するときの資源量（B_MSY）はそれぞれ管理基準値なので、どこかの表とかに同時に示されることもあると思いまうすがそのときにU_MSY=MSY/B_MSYになっていないと、おかしいんじゃない？ということになるかなと思って、、、。UMSYはそれ自体が何かに使われる管理基準値ではありませんので、そのような便宜的な定義で良いのではないでしょうか。（それぞれのやりかたでどのくらい値が違うかを見ておくのは重要ですが。。）

**Comment by ShotaNishijima** [comment]
了解しました
