### ISSUE TITLE
rda読み込み時のwarning

### ISSUE THREAD

**Issue by ichimomo** [ichimomo/frasyr#382]
frasyrをインストールしようとすると

'frasyr/inst/extdata/SRpma_BH_L1_AR1_outAR0.rda'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'frasyr/inst/extdata/SRpma_BH_L1_AR1_outAR1.rda'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'frasyr/inst/extdata/SRpma_BH_L2_AR0_outAR0.rda'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'frasyr/inst/extdata/SRpma_BH_L2_AR0_outAR1.rda'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'frasyr/inst/extdata/SRpma_BH_L2_AR1_outAR0.rda'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'frasyr/inst/extdata/SRpma_BH_L2_AR1_outAR1.rda'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'frasyr/inst/extdata/SRpma_HS_L1_AR0_outAR0.rda'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'frasyr/inst/extdata/SRpma_HS_L1_AR0_outAR1.rda' 

というようなwarningが延々と出ます．多分，テスト用に作ったrdaファイルのRバージョンが古いことへの警告だと思うんですが，新しいバージョンのRでファイルを作り直せばおさまるでしょうか？まだ警告段階なので必須ではないですが，わーっと出てきてちょっと煩いので，お暇なときに対応していただけると助かります．→　とりあえず再生産関係用のテストファイル用のrdaですかね．　　よろしくお願いします

**Comment by fshin3** [comment]
SRpma_*.rdaを作り直してみたんですが（R ver.4.0.0 on MacOS）、そのブランチを自分でインストールしたら他のrdaファイル全部でワーニング出てました。で、作り直したはずのSRpma_*.rdaの警告が消えてないんですよね。devtools::install_github("fshin3/frasyr@issue382")
どうしたものでしょう？

**Comment by ichimomo** [comment]
さっそく作業していただいてありがとうございます。てっきり、rdaを作ったときのRのバージョンのせいだと思ったんですが、違うんですかね、、。もう少しググって、なにか対処法わかったら対処するようにしましょうか。ペンディングだけどissueはオープンのままにしておきます。

**Comment by Rindrics** [comment]
Docker で作ったらいいですね

**Comment by Rindrics** [comment]
事業としての標準バージョンは何でしょうか？もしよければ、そのバージョンのDocker から生成して更新します。

**Comment by fshin3** [comment]
Description: Estimating stock status with stock assessment models and calculating RPs and ABC for Japanese fisheries management
Depends: R (>= 3.5.0)
にして回してみる。

**Comment by fshin3** [comment]
DESCRIPTIONの修正で解消されました。
