### ISSUE TITLE
モデル診断のグラフreturn()時のエラー

### ISSUE THREAD

**Issue by Rindrics** [ichimomo/frasyr#386]
https://github.com/ichimomo/frasyr/blob/dev/R/rvpa.r#L1276
~どうしてNULLになってるのかも含め調査中~ <- これは勘違いでした、ごめんなさい

https://github.com/ichimomo/frasyr_tool/issues/169 と関連

**Comment by KoheiHAMABE** [comment]
`index_name = NULL` のことでしょうか？
- vpa関数内では資源量指数の名前見たいのを指定する引数がない
- vpa関数と共に出てくる残差プロットは担当者がフィッティング確認するもので、オフィシャルに提出することを想定していない（それはplot_residual_vpaを直接使って欲しい）

といったところが理由です。NULLにしても関数内でIndex01, Index02・・・といった形で自動で生成されます

**Comment by Rindrics** [comment]
@KoheiHAMABE すいません、エラー箇所を見誤ってました。

# 状況
https://github.com/ichimomo/frasyr_tool/issues/169 対応中

- スクリプトエラー箇所
https://github.com/Rindrics/frasyr_tool/blob/085ed760efeb70863e4c6e2917a8e443cc36fe45/script_SA2020/stock_assessment.R#L169-L182

- コードエラー箇所: 
https://github.com/ichimomo/frasyr/blob/5ac82669126338af5f9b48315305b4121d579fdd/R/diagnostics_vpa.R#L715-L719

**Comment by Rindrics** [comment]
一旦報告、エラーメッセージ調査します

**Comment by KoheiHAMABE** [comment]
`geom_smooth()` using method = 'loess' and formula 'y ~ x'

これ自体は、スムージングが上手く行っていないだけで、そのデータじゃうまいことスムージングの推定ができないよというメッセージですね

残差プロット自体はされていますか？（横軸時系列、縦軸対数残差の図です）

**Comment by Rindrics** [comment]
ありがとうございます。残差プロットは出ていますよ。
（すいません、警告

**Comment by Rindrics** [comment]
他のタスクあるので一旦ストップしています。

**Comment by KoheiHAMABE** [comment]
承知しました

Error in gList(list(grobs = list(list(x = 0.5, y = 0.5, width = 1, height = 1,  : 
  only 'grobs' allowed in "gList"

こちのエラーも同じ場所で出ますか？
初見なのでちょっと調べてみます

**Comment by Rindrics** [comment]
はい、そのエラー、同じ箇所で出ています。return()時です。申し訳ありません。
ブランチは frasyr_tool の hokke_dohoku です（hokkeではありません）:bow:
git submodule update してください。

**Comment by KoheiHAMABE** [comment]
これ自分もローカルでhokke_dohokuブランチ作らないといけないんですっけ？
git checkout -b hokke_dohoku
git pull origin hokke_dohoku
git submodule update
ですか？

**Comment by Rindrics** [comment]
git fetch --all
git checkout hokke_dohoku
git submodule update
です！

**Comment by KoheiHAMABE** [comment]
ありがとうございます！開発側なのにお手数おかけしちゃってすみません笑

**Comment by KoheiHAMABE** [comment]
>     * スクリプトエラー箇所
>       https://github.com/Rindrics/frasyr_tool/blob/085ed760efeb70863e4c6e2917a8e443cc36fe45/script_SA2020/stock_assessment.R#L169-L182

これhokke_dohokuっぽくないのですが大丈夫ですか？

**Comment by Rindrics** [comment]
いやとんでもない！！！！ありがとうございます！！！

**Comment by Rindrics** [comment]
ああ間違い、すいません。太平洋マアジでした

**Comment by Rindrics** [comment]
maaji_pacific_hayashi を pushしますので、それをcheckoutお願いします

**Comment by KoheiHAMABE** [comment]
分かりました！

**Comment by KoheiHAMABE** [comment]
これRprojで作業しているとディレクトリの変更できない感じですか？

**Comment by KoheiHAMABE** [comment]
データは読み込めているので問題ないです
そしてエラーまで無事に（？）至れました

**Comment by Rindrics** [comment]
>これRprojで作業しているとディレクトリの変更できない感じですか？
setwd()すればできますよ。あ、どの階層のRprojお使いでしたっけ？

**Comment by Rindrics** [comment]
>データは読み込めているので問題ないです
そしてエラーまで無事に（？）至れました

再現できたとのことでまずは安心（？）しました。
もしできたらでいいので、なにか情報得られましたらご提供いただけませんか？

**Comment by KoheiHAMABE** [comment]
簡単かと思いましたが、ちょっとすぐには分からないですね
gridExtra::grid.arrange関数のせいだろと思ったのですが、手動ではめると普通に動くんですよね

**Comment by KoheiHAMABE** [comment]
分かった気がします。多分frasyrのバージョン問題と関連していますが,
エラーのShow Tracebackするとこうなってすじゃないですか
```
2.  gridExtra::grid.arrange(graph$year_resid, graph$fitting_CPUE,
           graph$abund_CPUE) at rvpa.r#1285
```

本来今のコードって$fitting_Indexと$abund_Indexってなっているんですよ（CPUEがIndexに変わっています）
https://github.com/ichimomo/frasyr/blob/f3053edd59cd3eb5bbc20fc230c954083ab1735e/R/rvpa.r#L1285

frasyrファイル内のR/rvpa.rの1285行目もCPUEなので古いままなんですよね

**Comment by KoheiHAMABE** [comment]
今、頻繁にプルリク出して、既に
- R/graphic.r
  - plot_vpa関数の修正
- R/rvpa.r
  - vpa関数の修正
  - この箇所は修正してからリリースした気もするのですが
- R/diagnostics_vpa.r
  - ほとんどの関数に修正が一度入っている
  - ブートストラップとジッターはいじっていない

という感じで、バグ修正と要望修正でかなり変更しているので、一度
**gitで管理している魚種はfrasyr最新版の更新**
を行って頂けるとこの辺解消されるかと思います

**Comment by Rindrics** [comment]
Oh...ありがとうございます。
今見たら、たしかにこのブランチは2つ前のマージコミットを指していました。

今重視すべきは、業務の追跡可能性よりも、担当者がさっと手元でインストールする身軽さですね。
submoduleの操作を一人がやる運用では、そこにボトルネックが集中します。
今はまだ時期じゃないことがよくわかりました。
ありがとうございます。
