### ISSUE TITLE
質問: 引数 abund とuse.index の関係 in rvpa()

### ISSUE THREAD

**Issue by Rindrics** [ichimomo/frasyr#387]
# 状況
（ホッケ道北 https://github.com/ichimomo/frasyr_tool/issues/172 に対応中）

現在の設定: 
- `use.index = 21`
- `abund = 5`

https://github.com/ichimomo/frasyr_tool/blob/449aa77f0156f43152d67295b74d4c0b6e037827/script_SA2020/stock_assessment.R#L56-L57

## エラーメッセージ
```Error in if (abund == "N") res <- colSums(naa[min.age:max.age, ], na.rm = TRUE) : 
  missing value where TRUE/FALSE needed
```

## エラーの原因
1. 長さが5しかない`abund` オブジェクトに対して、`abund[21]` と範囲外インデックスを指定しているため、`abund`が`NA`になる:
https://github.com/ichimomo/frasyr/blob/5ac82669126338af5f9b48315305b4121d579fdd/R/rvpa.r#L587
1. `if(NA == "N")` が評価されて停止:
https://github.com/ichimomo/frasyr/blob/5ac82669126338af5f9b48315305b4121d579fdd/R/rvpa.r#L231

# 質問
@ichimomo 関数の修正が必要でしょうか？
それとも、関数を正しく使えていないだけでしょうか？ご教示ください。

**Comment by KoheiHAMABE** [comment]
abundって数字でなくてc("N","N","N","B","B")みたいな引数でなかったでしたっけ？

**Comment by Rindrics** [comment]
@mmitsuyo すみません、`vpa()`の使い方を教えていただけないでしょうか。
https://github.com/ichimomo/frasyr_tool/blob/hokke_dohoku/script_SA2020/stock_assessment.R で作業中、https://github.com/ichimomo/frasyr_tool/blob/hokke_dohoku/script_SA2020/stock_assessment.R#L51-L70 が止まっています。

**Comment by OkamuraHiroshi** [comment]
indexが一個なのに、abundがボボボボボとなってるのが駄目なのでは？

2020年6月30日(火) 17:14 Akira Hayashi <notifications@github.com>:

**Comment by Rindrics** [comment]
ありがとうございます！！なんと恥ずかしい...

**Comment by Rindrics** [comment]
今度別のとこでエラーでましたが、本件closeします。ありがとうございました。
