### ISSUE TITLE
コンフリクトの結果

### ISSUE THREAD

**Issue by ichimomo** [ichimomo/frasyr#39]
vignetteの内容がコンフリクトの結果こんなになってしまったんですがどうすればいいでしょうか？

https://github.com/ichimomo/frasyr/blob/ba7de05ab1a6c85695b29b91002936335a681e55/vignettes/estMSY.Rmd#L1-L6

**Comment by kikirinrin** [comment]
意図と合うように編集すればいいだけですよ．

HEADを活かすなら
```
 title: "MSY管理基準値計算" 
```
コミット `07acd67cd1b870e640bfc8cb56065a43521ba244` を活かすなら
```
 title: "future関数を使った将来予測と管理基準値計算（簡易版）" 
```
それだけです．

**Comment by ichimomo** [comment]
お返事ありがとうございます．ファイルの中身を直接編集して，必要ない部分を消してしまえばいいということでしょうか？

**Comment by kikirinrin** [comment]
けっこう前のコンフリクトみたいですね．
https://github.com/ichimomo/frasyr/commit/f5efecb321c8f81652251fd1946dffe0d0265f48#diff-cafc2bd151c2a6a30078086d1eacc71b

コンフリクトが起きた時なら，気の利いたエディタならさくさく解決していけるのです

**Comment by kikirinrin** [comment]
けっこうコンフリクト箇所が多いですね．
いろんなところに取り込まれてしまっているので，下手に`reset` & 強制 `push` するより，
- `master` から `bugfix` を切る
- 手作業で編集
- `master` 含む各ブランチにマージ

がシンプルなのではないでしょうか．
`<<<<` とか `====` を検索して，頑張るしか無いですね．
意図は「常にHEADを活かす」で合っていますか？

**Comment by kikirinrin** [comment]
ちなみに，ローカルでpullして，コンフリクトが起きたまさにその時なら，

- use their change
- use our change

を使ってサクサク解決していけます．

**Comment by ichimomo** [comment]
どうもありがとうございます．とりあえず，手動で修正します．．．
