### ISSUE TITLE
retro.est関数におけるlast.catch.zeroオプション

### ISSUE THREAD

**Issue by ShotaNishijima** [ichimomo/frasyr#406]
続けざまのissueすみません。retro.est関数でlast.catch.zeroオプションをvpaで使っている場合、
https://github.com/ichimomo/frasyr/blob/c9e30546db7b1813373870a4336e504d42c1b0a5/R/rvpa.r#L1552
ここでFALSEになるようになっています。ただissue #398 で議論したように、資源評価の更新として考えるのであれば、ここはFALSEにしなくていいのではないかなと思います。last.catch.zeroオプションは最終年のcaaを0として、その1年前のFを推定する引数だと思います。
それから、その場合のMohn's rhoはどこを見ればいいのかなというのも気にしています。少なくともFは1年前になるのではないでしょうか？しかし、結構細かい点でジェネラルにどこまで対応すべきかは難しい所です。関係するのは僕が把握してる限り、マイワシ太平洋、マサバ太平洋、ゴマサバ太平洋です。

**Comment by ShotaNishijima** [comment]
ごめんなさい、これは
https://github.com/ichimomo/frasyr/pull/405
で対応済みですね。ちょっとチェックしてみます。

**Comment by KoheiHAMABE** [comment]
もともとretro.est2という関数がlast.catch.zero=TRUE用にあったのですが、ほとんど同じですので途中でif文かましています(1557行目です)
とりあえず手元で動くことは確認しているのですが、西嶋さんにも確認して頂けると助かります。
エラー出るのではとハラハラで・・・
