### ISSUE TITLE
FのMohn's rhoの計算について

### ISSUE THREAD

**Issue by KoheiHAMABE** [ichimomo/frasyr#409]
https://github.com/ichimomo/frasyr/pull/405#pullrequestreview-444527826

マサバ太平洋はSSBは一年先ので見ていたので、SSBだけでも1年先を評価するオプションがあってもいいかと思いましたが、とりあえず不要だと思います。あと気になったのですが、Fも全年齢の平均でMohnを評価していますが、基本的に最高齢とその1個前のFは同じ（alpha=1の場合）ですよね？ですので最高齢も含めるとダブルカウントになりませんか？僕は自分の計算では除いてました。

この部分

**Comment by KoheiHAMABE** [comment]
コメント受けてこちらにissue作りました

全年齢のFが足せていればいいので、問題ないのかなと思ってました。
仮にalpha=0.9等の場合も、最高齢のFに一定数かけているだけですのでダブルカウントとは言いませんが、意味合いとして重複しているのかなという気がしました。
sum(F_retro[0:A-1])/sum(F_res[0:A-1])
とした方がいいのでしょうか？

認識違いでしたらすみません

**Comment by ShotaNishijima** [comment]
ただ、最高齢のも合わせたとしては間違いはないですよね。ですので、今のものをデフォルト設定として、最高齢のFもMohnの計算から除けるような引数をつけるのはどうでしょうか？
なんか口うるさいおじさんみたいになってきましたので、こちらで対応してプルリクしましょうか？

**Comment by ichimomo** [comment]
考え方の問題かなと思いますが、私としては、「問題の大きさ」を表すのであれば全Fを使ったほうが良いのかなと思いますが（つまり、プラスグループA歳としたとき、A歳とA-1歳のFを同時に過大推定するのは、A-2歳だけを過大推定するよりも問題が大きい＝より避けたいと考える）どうなんでしょうか、、

岡村さんの論文　ICES Journal of Marine Science (2017), doi:10.1093/icesjms/fsx089　では普通に全Fを平均してますね

ただ、どちらにせよ、2つの考え方があって2つのやり方があるのであれば、どちらを使うのかを明確にしておくのが良いかと思います。

**Comment by KoheiHAMABE** [comment]
西嶋さん、コード修正頂きありがとうございます。西嶋さんのコード、そのままichimomo/devにプルリクして頂いてもよろしいですか？オプションとして、あった方が自由度が高くていいですね。

レトロのFですが、寿命が短命で最高齢のFの推定誤差が大きくない種とかだと、最高齢のF抜いた方が他の年齢のFの影響をちゃんと見れたり（こんなイメージで合ってますかね）と、各資源で合わせて頂く必要がありそうな気がします
VPAの癖だったり、わが国でどんな特性の資源が多かったりするのか知らないので、どちらの方法を使うかはお二人の判断を仰ぎたく思います。

**Comment by ShotaNishijima** [comment]
間違ってichimomoのdevにそのままpushしてしまいました…。修正しますので、少々お待ちください
