### ISSUE TITLE
last.catch.zeroの時のdo_retrospective_vpa関数の作図

### ISSUE THREAD

**Issue by KoHMB** [ichimomo/frasyr#410]
https://github.com/ichimomo/frasyr/pull/405#pullrequestreview-444527826

do_retrospective_vpa()のグラフで気になったのはlast.catch.zeroのときも最終年の結果までプロットされることです。ですので、Mohnで出している結果と1年ずれてます。ここは分かりやすく、この引数を使っているときはすべて1年前までで合わせたほうがいいのではないでしょうか？添付した図のように、僕は最新年の加入にrec.new=1000とか適当に入れていたのでそれに合わせて変な図になってしまいます。

この部分

**Comment by KoheiHAMABE** [comment]
作図の修正をプルリク
明日の朝、travisがOKならマージ予定

**Comment by ichimomo** [comment]
これ、アサインされていますが、plot_vpaの仕様をそのように変更しようという提案になりますか？あ、でも、https://github.com/ichimomo/frasyr/blob/dd711236514c21b60181718d3f6cfefd508cddd1/R/graphics.r#L77
plot_year引き数があるので、レトロの関数内で制御できますか？

**Comment by KoheiHAMABE** [comment]
すみませんこちらのコメント、気付くより先にマージしてしまいました

**Comment by KoheiHAMABE** [comment]
レトロ関数内でいじってしまいました
https://github.com/ichimomo/frasyr/blob/11c830be479c65b82ea381f00133c00de1587f3e/R/diagnostics_vpa.R#L345-L350

plot_vpa関数はレトロ以外にも共通して使っている関数なので、あまり細かい仕様入れない方がよいかと思いました

**Comment by KoHMB** [comment]
issue解決しているのでcloseします
