### ISSUE TITLE
チューニングなしでlast.catch.zero=TRUEにするとssbの最終年にNAが入る?

### ISSUE THREAD

**Issue by ShotaNishijima** [ichimomo/frasyr#413]
チューニングなしでたぶんlast.catch.zero=TRUEにするとssbの最終年の1歳以上がNAになるみたいです。last.catch.zeroってチューニングのとき使うので問題ないような気がしますけど、naaとかbaaはちゃんと出ていて、maaも最終年まで入っているのにNAになるのが気になったので一応issueに上げておきます。ゴマサバ太平洋の2stepやるときの1段階目で確かめられます。
https://github.com/ichimomo/ABC2019/blob/nishijima/gomasaba-Pacific/nishijima/make_vpa.R
ここの85行目あたりの`res1.pgs$ssb`で確認できるかと思います。

**Comment by ichimomo** [comment]
@mmitsuyo さん、急ぎでないので、お時間あるときにちょっと見てみてください
