### ISSUE TITLE
kobeF.png　y=0のところに出る線

### ISSUE THREAD

**Issue by YodaMari** [ichimomo/frasyr#432]
神戸プロットの図を描画するとY=0のところでX軸に平行な線が描画されます。
禁漁水準のところまで引かれていて、HCRを描画していた時の残りではないかと思うのですが、
どうやったら消せるでしょうか。

今はこの線は必要ないと思うので、デフォルトで描画しないようにしてもらえると助かります。

**Comment by ichimomo** [comment]
これですね。
Bbanの値にマイナス値を入れれば消えるのではないかと推察していますので、27日までには修正するようにします。

![image](https://user-images.githubusercontent.com/44047915/88142546-a95a8600-cc30-11ea-8f9f-3397f91a0678.png)

**Comment by ichimomo** [comment]
https://github.com/ichimomo/frasyr_tool/pull/223/commits/0e9d8105891e2d1810942739d36d83a7b1c7e170
このコミットで修正し、1do_projection.rにも統合しました。
