### ISSUE TITLE
再生産関係のモデル診断をvignetteに入れる

### ISSUE THREAD

**Issue by ichimomo** [ichimomo/frasyr#442]

**Comment by fshin3** [comment]
@ShotaNishijima モデル診断のrmdをvignetteに入れ直しているんですが、wiki/Diagnostics-for-Stock-Recruitment-Relationships.htmlと/docs/SRR-guidline.htmlをみると、wikiのほうが関数になっていて新しいとみて良いですか？またQQplotは一様分布仮定の方で統一した方が良いでしょうか？

**Comment by ShotaNishijima** [comment]
wikiの方が新しいので、基本そっち使ってください。
QQplotは一様分布のみにした方が、L2・L1共通で比較できるのでいいかなと。

**Comment by ichimomo** [comment]
vignetteに入れるとcheckに時間がかかるので、frasyr_toolのほうで運用するようにしましょう
https://github.com/ichimomo/frasyr_tool/issues/313
