### ISSUE TITLE
チューニング指標値を2つ使うとplot_residual_vpa()でエラーが出る

### ISSUE THREAD

**Issue by aynigisu** [ichimomo/frasyr#447]
チューニング指標値を2つ使っているVPAの結果をplot_residual_vpa()に入れると、
以下のエラーが出て、途中で止まってしまいます。
```
plot_residual_vpa(out1)
 if (sum(tmp == "N") == 0) { でエラー: 
   TRUE/FALSE が必要なところが欠損値です 
```
チューニング指標1本の時は問題ありませんでした。
お手数をおかけしますが、よろしくお願いいたします。

**Comment by KoheiHAMABE** [comment]
返信遅れてしまい、申し訳ありません。
out1はVPAの実行結果かと思いますが、そのコードを教えて頂けませんでしょうか。

よろしくお願いします。

**Comment by KoheiHAMABE** [comment]
もしかすると、vpa関数内のabundという引数に1つしか値を与えていない、ということはありませんでしょうか？
vpa(・・・, abund = c("N", "N", ),・・・)
のように、指数の数分入力する必要がありまして、
- "N": 尾数スケール
- "B": 重量スケール
- "SSB": 親魚重量スケール

と適宜、値を変えて与える必要があります。

違っていました申し訳ありません
一度ご確認のほど、よろしくお願い致します。

**Comment by aynigisu** [comment]
>もしかすると、vpa関数内のabundという引数に1つしか値を与えていない、ということはありませんでしょうか？
全くその通りでした！abundに指数分引数を与えたら、問題なく動きました。
お忙しいところ、ご面倒をおかけして、大変失礼いたしました。迅速なご対応感謝いたします。
