### ISSUE TITLE
途中でプラスグループが変わるときの計算方法について

### ISSUE THREAD

**Issue by ichimomo** [ichimomo/frasyr#451]
以前のやりかたでもできるようにオプションを追加する

**Comment by osamusakai** [comment]
よろしくお願いします。スケトウ太平洋では以前の数式を引き続き使用しております。具体的には以下のような形になっています；
![image](https://user-images.githubusercontent.com/5091111/91123103-f968b480-e6d6-11ea-8086-e9a2ff88b768.png)

なお、プラスグループを延長している年（上図では1997・1998）はプラスグループのFが一切若い年齢のFと等しいという仮定は置かない形になります。
