### ISSUE TITLE
test-data.handler.Rでwarning多数

### ISSUE THREAD

**Issue by ichimomo** [ichimomo/frasyr#455]
testを走らせているとtest-data.hander.Rでwarningがたくさん出てくるのですが、大丈夫でしょうか？
ちょっと確認いただいてもいいですか？
また、wariningが期待通りの動作ならexpect_warningとかを使うのが良いのではないかと思います。

お時間あるときで大丈夫です。

**Comment by mmitsuyo** [comment]
https://github.com/mmitsuyo/frasyr/commit/c27a467495eef6f9100d099829885fc6c595870f
にて対応済みなのでissueはcloseさせていただきます．ありがとうございました．
