### ISSUE TITLE
plot_HCRのFtarget

### ISSUE THREAD

**Issue by ShotaNishijima** [ichimomo/frasyr#46]
plot_HCRのFtargetの定義が違う気がします。先日お聞きしたときはFtarget = beta*Fmsyということで、岡村さんが書かれた新ABCルールの文書もそうなっていますが、このプログラムだとFtarget = Fmsyとなっているようです。どちらが正しいのでしょうか…？

**Comment by ichimomo** [comment]
新ルールでのその定義はけっこう後に決まった（5月）ので、関数作成時（4月）にはまだそのへんあいまいでした。plot_HCRは福井さんが作ってくれたので、修正は福井さんにお願いしてもよいでしょうか？？

**Comment by fshin3** [comment]
この関数の中ではFmsyが定義されておらず、引数としてよみこんだFtargetに対してbetaをかけた値をmultipliyer to Fcurrent (multi2currf) として出力しています。
言葉の定義が理解できていないのですが、この関数で出力しているmulti2currfが Ftargetという解釈をして良いですか？
そうであれば今の関数でFtargetをFmysと書き換える作業をします（この関数を呼び出すときの引数もFmsyとする必要があります）。

**Comment by ShotaNishijima** [comment]
今のバージョンで、FtargetとなっているものをFmsyに、beta*FtargetとなっているものをFtargetに変えればいいんだと思います。

**Comment by fshin3** [comment]
コメントありがとうございます。plot_HCRの引数にあるFtargetをFmsyに変更し、関数内でFtarget<-beta*Fmsyを定義し、該当箇所を置き換えました。ただ、utilities.r全体にわたってbetaFtargetが使われているように思います。utilities.r全体的に命名の変更を行った方が良いのでしょうか？

**Comment by ichimomo** [comment]
どうもありがとうございます．
ファイル全体での命名の統一は，後日一括しておこなおうと思います．
