### ISSUE TITLE
1:length()の代わりに用心深くseq_len関数を使う

### ISSUE THREAD

**Issue by yukio-takeuchi** [ichimomo/frasyr#462]
1:length()あるいは、1:nrow()
という形で、数列を発生させるコードは、
何カ所か使用されています。普通は問題は無いですが、
length()もしくは、nrow()が、0でも、エラーを出さずに
1,　0
を発生してそのまま動くので、
予想外の問題を避けるために、
seq_len(length())
と書き換えた方が、ロバストなコードになります。

**Comment by ichimomo** [comment]
#530 でfuture.rについては対応。順次対応すること
