### ISSUE TITLE
オフラインでtestのエラー

### ISSUE THREAD

**Issue by fshin3** [ichimomo/frasyr#473]
テスト実行、あるいはチェック実行時にオフラインだとdata handlerでエラー。

**Comment by mmitsuyo** [comment]
それは，コード中で，
library(TMB) 
use_rvpa_tmb()
をしているからですかね．　どうしたらよいのかご助言お願いします・・・

**Comment by Rindrics** [comment]
多分 [vignette](https://github.com/ichimomo/frasyr/blob/5323b10f78e536d8505fc962f9b37d8d7f797ee8/vignettes/vpa.Rmd#L30-L33) でGitHubからcsvを読んでるからだと思います。

[test](https://github.com/ichimomo/frasyr/blob/5323b10f78e536d8505fc962f9b37d8d7f797ee8/tests/testthat/test-data.handler.R#L6) でやられているように、 `inst/extdata` から `system.file()`  を使って読めば直ると思います。
