### ISSUE TITLE
vpa()でlast.catch.zero=TRUE & sel.update=TRUEの時の加入量

### ISSUE THREAD

**Issue by ShotaNishijima** [ichimomo/frasyr#474]
`vpa(..., last.catch.zero=TRUE, sel.update=TRUE)`
のとき`rec.new=NULL`でも最新年の加入量の値が入る。どうやら`rps.year=2001:2010`がデフォルトとなっており、この期間のrps中央値から計算されている模様。ただしsel.updateでないときには0が入るようになっている。sel.updateによらず同じ対応にしたほうが良いと思いますし、勝手にrps.yearから値が与えられるのはよくないのではないかと思います。0よりNAの方がよいということはないでしょうか…？

**Comment by ichimomo** [comment]
ご報告ありがとうございます。そうですね。どんなときでもNAが入るようにしたほうが良いかと思います。宮川さん，修正お願いできますか？

また，そもそもlast.catch.zero=TRUEで出力されたVPAに対して，将来予測のプログラムのほうは対応してないんですよね，，（太平洋マイワシもそうだったような）　将来予測との連携については，私のほうで考えておきます。

**Comment by ShotaNishijima** [comment]
そう、将来予測のところも注文をお願いしようかと思ったんですが、なんかバグ探しばっかやってるクレーマーみたいになりそうなので遠慮しておきました。last.catch.zero使っているのにも僕が知ってる限り2種類あって、ひとつはマイワシ太平洋・ゴマサバ太平洋でvpaの最新年の結果は将来予測に用いない場合（チューニングのみに使用）で、もうひとつはマサバ太平洋でこれは加入の最新年の予測までするので将来予測は最新年のF=Fcurrentからで、加入は翌年から将来予測することになります（本当にそれでいいかは置いといて今のところそれで計算しています）。ややこしいですが、よろしくお願いします。
前者であればvpaでno.estとか使ってvpaデータを1年削った結果にしてしまうとか、後者であれば最新年のFにFcurrentを入れるとかで、vpaの方で対処するのでも良さそうですけどね。
