### ISSUE TITLE
レジーム分割の再生産関係モデルの診断ができない？

### ISSUE THREAD

**Issue by JK-junkin** [ichimomo/frasyr#478]
カタクチイワシ太平洋系群です。変な質問でしたらすみません。

 [Wiki](https://github.com/ichimomo/frasyr/wiki/Diagnostics-for-Stock-Recruitment-Relationships)の説明に従って、レジーム分割した場合の再生産関係のモデル診断を行おうとしましたが、`autocor.plot()`以外、処理が途中で止まってしまいます。

frasyrの最新devあるいはmasterブランチをインストールして試しましたが、いずれも同じ症状でした。
開発ログを遡って、関係するコミットを探索・`git revert`する作業をLocalで実施しようと思っていますが、
そもそも使い方が違っているなど、もしお気付きの点がございましたら、コメントをいただけますと幸いです。:bow:

---

**下記、実行スクリプトです。**（処理が止まった関数は # でコメントアウトしている。）
```
# ある設定のres_SR_MSY（res_SR.rda）を読み込む
    load(reslist[i]) 

#     check.SRfit(res_SR_MSY, output = TRUE,
#                 filename = file.path(output_folder, "check"))

    ## 1. 残差の分布
#     check.SRdist(res_SR_MSY, output = T,
#                  filename = file.path(output_folder, "resid_dist_check"))

    ## 2. 残差の自己相関プロット
    ### 再生産関係との残差
    calc.residAR(res_SR_MSY, per_regime = T)
    autocor.plot(res_SR_MSY, output = T,
                 filename = file.path(output_folder, "devianceAR"))

    ### 自己相関推定後の残差
    autocor.plot(res_SR_MSY, output = T, use.resid = 2,
                 filename = file.path(output_folder, "residAR"))

    ## 3. ブートストラップ
#    boot.res1 <- boot.SR(res_SR_MSY, n = 100, method = "p") # パラメトリック
#    boot.res2 <- boot.SR(res_SR_MSY, n = 100, method = "n") # ノンパラ (L1 vs L2に)
#    bootSR.plot(boot.res1, output = TRUE,
#                filename = file.path(output_folder, "para_boot"))
#    bootSR.plot(boot.res2, output = TRUE,
#                filename = file.path(output_folder, "nonpara_boot"))

    ## 4. ジャックナイフ
#     jack1 <- jackknife.SR(res_SR_MSY, is.plot = TRUE, output = TRUE,
#                           filename = file.path(output_folder, "jack"))

    ## 5. プロファイル尤度
#     prof1 <- prof.likSR(res_SR_MSY, output = TRUE,
#                         filename = file.path(output_folder, "proflike"))

    ## 6. パラメータ間相関
#     res_corSR <- corSR(resSR = res_SR_MSY)
```

**Comment by fshin3** [comment]
レジームありでのcheck.SRfitなどの計算はかなりの計算負荷がかかります。最新のdevブランチでテストをかけているので、このブランチでいいはずなんですが、すみません、ぱっとは原因がつかめません。途中で止まる時のエラーメッセージなどありましたら情報をお願いします。

また、テストデータとしてdata("res_vpa")でres_vpaをloadし、これで
testSRdata <- get.SRdata(res_vpa)
testR1 <- fit.SRregime(testSRdata, SR = "HS", method = "L1", regime.year = c(2005), regime.par = c("a", 
    "b", "sd")[1:3], use.fit.SR = TRUE, regime.key = c(0, 1))
testR2 <- fit.SRregime(testSRdata, SR = "HS", method = "L1", regime.year = c(2005), regime.par = c("a", 
    "b", "sd")[2:3], use.fit.SR = TRUE, regime.key = c(0, 1))
とした場合の（wiki通り）
check.SRfit(testR1,output=TRUE,filename="test_R1")
check.SRfit(testR2,output=TRUE,filename="test_R1")
は回りますでしょうか？止まってしまうでしょうか？
お手数をおかけしますがご確認をお願いします。

**Comment by JK-junkin** [comment]
@fshin3 様

素早いご返信、ありがとうございます！

特にエラーが出る訳ではありません。計算負荷が高いということですので、一晩計算させておいて、明日確認いたします。
（レジーム非分割のときはあまり時間がかからなかったので、何かおかしいのかな？と思ってしまいました。すみません。。。:bow:）

教えていただいたテストコードを回しています。結果が出ましたらまたご報告いたします。

**Comment by JK-junkin** [comment]
テストコード、`check.SRfit(testR1,output=TRUE,filename="test_R1")`の方だけですが、計算が無事に終わりました。
**単に計算に時間がかかっていた**だけでした。早とちりで、申し訳ありませんでした。:bow: お騒がせしました。。。

Issueをcloseします。

**Comment by fshin3** [comment]
あ、ちなみに示したテストだとtestR2のほうがもっと時間かかります。念の為。

そして、それをbootstrapにすると、、、あまりにも時間がかかりすぎる場合、実用に耐えないケースもあるということを周知する必要に迫られるかもせませんので、おしらせください。

**Comment by JK-junkin** [comment]
@fshin3 様

お返事下さり、ありがとうございます！結果報告のため、IssueをReopenします。

実データでのモデル診断を昨晩実施しました。計算時間は一つの設定（`res_SR.rda`）あたり40分程度かかりました。
1. `check.SRfit()`は無事に終わりました。
2. `prof.likSR()`（尤度プロファイルの計算・作図）の部分で下記のようなエラーが出て、計算が止まっていました。  
結果の図も出力されていません。
```
optim(x, obj.f, par_a = ba.grid[i, 2], par_b = ba.grid[i, 1],  でエラー:           
 non-finite finite-difference value [2]
```

現在、**テストデータで確認しています。**

---

参考までに、実行したモデル診断のコードを残します。
```
## 日付で絞り込む -------------------------------------------------------
date_from <- 20200928
date_to   <- 20200928
dates     <- seq(lubridate::ymd(date_from), lubridate::ymd(date_to), by = "day")
fdates    <- paste(format(dates, "%Y%m%d...."), collapse = "|")
pattern   <- paste0("(?<=(-Regime-)).*(", fdates, ")")

reslist <- dir("out/AnchoP", recur = T, pattern = "res_SR.rda", full = T)
reslist <- reslist[stringr::str_detect(reslist, pattern)]
output_folders <-  stringr::str_remove(reslist, basename(reslist))

for(i in seq_along(reslist)) {
    load(reslist[i])
    output_folder <- output_folders[i]

    ## 0. モデルの概要
    check.SRfit(res_SR_MSY, output = TRUE,
                filename = file.path(output_folder, "check"))

    ## 1. 残差の分布
    check.SRdist(res_SR_MSY, output = T,
                 filename = file.path(output_folder, "resid_dist_check"))

    ## 2. 残差の自己相関プロット
    ### 再生産関係との残差
    calc.residAR(res_SR_MSY, per_regime = T)
    autocor.plot(res_SR_MSY, output = T,
                 filename = file.path(output_folder, "devianceAR"))

    ### 自己相関推定後の残差
    autocor.plot(res_SR_MSY, output = T, use.resid = 2,
                 filename = file.path(output_folder, "residAR"))

    ## 3. ブートストラップ
    boot.res1 <- boot.SR(res_SR_MSY, n = 100, method = "p") # パラメトリック
    boot.res2 <- boot.SR(res_SR_MSY, n = 100, method = "n") # ノンパラ (L1 vs L2に)
    bootSR.plot(boot.res1, output = TRUE,
                filename = file.path(output_folder, "para_boot"))
    bootSR.plot(boot.res2, output = TRUE,
                filename = file.path(output_folder, "nonpara_boot"))

    cat(i, "\n")
    ## 4. ジャックナイフ
    jack1 <- jackknife.SR(res_SR_MSY, is.plot = TRUE, output = TRUE,
                          filename = file.path(output_folder, "jack"))

    ## 5. プロファイル尤度
    prof1 <- prof.likSR(res_SR_MSY, output = TRUE,
                        filename = file.path(output_folder, "proflike"))

    rm(res_SR_MSY)
    cat(i, reslist[i], "is finished.\n")
}
```

**Comment by JK-junkin** [comment]
プロファイル尤度の描画、テストデータではうまくいきました。

#### ...... 実データでエラーが出る原因を探っています ......
- `fit.SRregime()`の`regime.par`はa, b, sdの3つを指定して実行したので、この設定については上記`testR1`と同じ。
- 実データは`fit.SRregime(..., regime.year = c(1988, 2014), ...)` としており`testR1`とは異なる（出力名は`res_SR_MSY`）。
- `str(testR1)`と`str(res_SR_MSY)`を比較すると、`testR1$sd.pred`の要素数は2であるのに対し、`res_SR_MSY$sd.pred`の要素数は1（res_SR_MSYは`SR = "BH"`の結果）。
- `fit.SRregime(..., SR = "BH", ...)`の結果を使うと上記のエラーが出たが、`SR = "HS"`では出なかった。:arrow_right:**原因はこれか！？**
- `fit.SRregime(..., SR = "RI", ...)`の結果を使うと上記のエラーが出る。

**Comment by JK-junkin** [comment]
### エラー原因特定
レジーム分割の結果でプロファイル尤度の描画が失敗するのは、`SR = "BH"` または `SR = "RI"` の場合でした。

**Comment by JK-junkin** [comment]
原因がわかりましたので、新たにIssueを立てます。
