### ISSUE TITLE
レジーム分割の再生産関係（BH、RIの場合）：プロファイル尤度の図が描けない

### ISSUE THREAD

**Issue by JK-junkin** [ichimomo/frasyr#479]
`fit.SRregime(..., SR = "BH", ...)`または`fit.SRregime(..., SR = "RI", ...)`の結果を`prof.likSR()`に渡すと
```
 optim(x, obj.f, par_a = ba.grid[i, 2], par_b = ba.grid[i, 1],  でエラー: 
  non-finite finite-difference value [2]
```
というエラーが出ます。
`SR = "HS"`の場合では問題ありません。

Related to #478

**Comment by fshin3** [comment]
ありがとうございます。確認します。

**Comment by JK-junkin** [comment]
ありがとうございます！！どうかよろしくお願いいたします。:bow:

**Comment by fshin3** [comment]
@ShotaNishijima さん
作成してもらったprof.likSR関数で、SR=BH or RI (regime)のときに以下のoptimで収束しないと出るのですが、
https://github.com/ichimomo/frasyr/blob/53c5191fc36fcce52ee9e8487b416928466e2bff/R/stock_recruit.r#L1649-L1650

optimのmethod="BFGS"でなく"Brent"の方で計算を試した跡があるのでお聞きしますと、こちらでは収束したとかありますか？もしくは収束したけど時間かかりすぎとかありました？

**Comment by ShotaNishijima** [comment]
Brentは一変数の場合で、今はfit.SRregimeで複数あると思うので下だと思うんですが、これ結局if文で変数の数で分けてる意味がない感じですね。どういう経緯でそうしたかを忘れてしましましたが…。
BHとRIでダメということはbの値がものすごく小さくなっていないでしょうか？元々の推定はlog(b)で推定しているので、0になりきることは無いんですが、実際にはb≈0で、プロファイル尤度の計算ではリンク関数を噛ませないで推定してるんでその辺が理由でerrorになるのかもです。

**Comment by fshin3** [comment]
ありがとうございます。サンプルデータでエラー再現してみてるんですが、bが小さいですね。リンク関数噛ませてみます。

**Comment by ShotaNishijima** [comment]
bが小さいということは推定自体が上手くいっていないに等しいようなもんなんで、プロファイル尤度も何も無いような感じがしますね。ちょっとそういった診断や、そういう場合はプロファイル尤度を飛ばすみたいなことしてもいいのかもしれないです。
追記：推定が上手くいっていないというか、最小値になってるとか端点に達しているみたいな感じです。

**Comment by fshin3** [comment]
@JK-junkin さん
いま計算で問題がでているものはbが結構小さいですか？診断かけてるということは、候補となっているということですか？それともざっと診断まで計算してみているということでしょうか？そこらへんを状況に合わせて考える必要がありそうです。

**Comment by JK-junkin** [comment]
@fshin3 さん

お時間を割いて下さり、ありがとうございます！
レジーム分割でRI・BHの場合、b は かなり小さいです。1.0e-5程度です。HSは50000など、0より大です。

ざっと診断までしている、という感じです。
色々な設定の組み合わせを実行して、それらの結果を比較しているという段階なので、
bの値で判断できるようであれば、必ずしもこの図を描く必要はありません。

**Comment by fshin3** [comment]
いったん上記コメントのようにプロファイル尤度飛ばす感じで考えてみてください。ご指摘の点はとりあえずリンク関数噛ませるなどしてみたいと思います。（data(res_vpa)でロードできる参考データでwikiの通りにやれば、少なくともregimeなしではbが小さくてもprof.likSRは機能していますので、そちらに揃える形で。）SR=BH,RIでbがかなり小さく推定された場合、その結果の採択に難ありの可能性があることをwikiやvignetteに追記しておきます。

**Comment by JK-junkin** [comment]
> いったん上記コメントのようにプロファイル尤度飛ばす感じで考えてみてください。ご指摘の点はとりあえずリンク関数噛ませるなどしてみたいと思います。（data(res_vpa)でロードできる参考データでwikiの通りにやれば、少なくともregimeなしではbが小さくてもprof.likSRは機能していますので、そちらに揃える形で。）SR=BH,RIでbがかなり小さく推定された場合、その結果の採択に難ありの可能性があることをwikiやvignetteに追記しておきます。

本当にありがとうございます。
そういたします。条件分岐（エラーハンドリング）して、bが小さすぎる場合には描かないようにしようと思います。

**Comment by JK-junkin** [comment]
**追記**

> レジーム分割でRI・BHの場合、b は かなり小さいです。1.0e-5程度です。HSは50000など、0よりかなり大です。

再生産モデルの式を考えれば、RIやBHのbが小さいのは当たり前でした。@fshin3 さんも指摘しているように、レジーム分割しないときはBH・RIでもb = 1e-5とか描けているので、原因はbが小さすぎるためとも限らないようです。

検討したシナリオのレジーム分割のBH・RIのbは軒並み1.0e-4, 5, 6程度だったので、データセットから描画にうまく受け渡しができていない可能性があります。

**Comment by fshin3** [comment]
@JK-junkin さん

おしらせありがとうございます。prof.likSR関数で、あらかじめレジームを分けたものをfit.SRで推定してそれぞれのレジームごとにprof.likSRにかけるとお知らせいただきましたようにbが小さくてもうまく回ることを確認しています。@ShotaNishijimaさんが書かれていたようにprof.likSRでの推定では細かいところまで対応していないところが原因かと。以前のfit.SRのオプションで今はデフォルトになっている、rep.opt（パラメータ推定を収束するように繰り返す）をprof.likSRのレジームの方に入れてみようかなと思っています。やっぱり計算は重くなりますけど。

**Comment by fshin3** [comment]
@ShotaNishijima さん

prof.likSRのregimeありでrep.opt=Tを入れてみたのですが、確認してもらってよいでしょうか？
https://github.com/fshin3/frasyr/blob/ee635d1e25803467df650b20ca13169d97253d68/R/stock_recruit.r#L1681

これで計算しても最尤推定値にはいかないんで、どこか間違ってると思うんですが、どこが違うのか分からなくて。

よろしくお願いします。

**Comment by ShotaNishijima** [comment]
HSのときはb=min(SSB) + (max(SSB)-min(SSB))/(1+exp(-x))としたときのxを推定しているのでこれでいいんですかね？
https://github.com/ichimomo/frasyr/blob/e902ce36b4eb503d5acdb833144e3f06a0b0267b/R/stock_recruit.r#L222

**Comment by fshin3** [comment]
なるほど、そのままfit.SRのオブジェクト持ってくるだけじゃダメですね。a,bの片方固定しないと。ありがとうございます。

**Comment by fshin3** [comment]
@JK-junkin さん
prof.likSRの最適化オプションを"SANN"にして結構無理やり推定することをしてみているんですが(3GHz CPU, 16G メモリで丸2日とかかります)、aとbの相関が強く、かつbの尤度プロファイルは広い範囲にわたっている感じです。もしかしてbの大小に関わらず、推定した結果、観測データがHSでいう折れ点より小さいところに来てしまっていませんか？そうするとa,b間の相関が強く、optimで推定しづらい＆推定が不安定な状況になっているかもしれません。結果をプロットしてみてデータがほぼ直線に乗るならその時点でHS選択が視野に入るかと思います。

**Comment by JK-junkin** [comment]
> prof.likSRの最適化オプションを"SANN"にして結構無理やり推定することをしてみているんですが(3GHz CPU, 16G メモリで丸2日とかかります)
> ...
> 結果をプロットしてみてデータがほぼ直線に乗るならその時点でHS選択が視野に入るかと思います。

ご多用中にも関わらず、ご確認くださりありがとうございます！
当資源の再生産関係はほぼ直線に乗ると思うので、ご指摘内容を参考にさせていただきます。 :bow:
