### ISSUE TITLE
data.handlerを頑健に

### ISSUE THREAD

**Issue by ichimomo** [ichimomo/frasyr#489]
data.handlerなんですが，データとして与えるcaa, maa, Mの行名（年齢）・列名（年）がデータ間で異なっている場合，
エラーを出して止まるようにしていただいてもよいでしょうか？　さきほど，一部データで間違った行名が入っている場合でも普通にＶＰＡ関数は動くけど，その結果を別関数（Generation.Time）に入れたときにエラーが出てしまうという状況を報告いただきましたので．．．

data.handlerを見ると，maa, Mは行列でなくてベクトルでも可，という仕様になっているので，maaとＭが行列の場合にはcaaと行列名が一致しなければいけない，という仕様になるでしょうか．．．（または，暗黙にmaaとＭの行列名をcaaの行列名で置き換えてしまうか．．）

そのさい，林さんから教わったasserthatパッケージの関数を使うと良いと思います（stopifnotと同じだけどもっと良いみたい）　https://www.r-project.org/nosvn/pandoc/assertthat.html

例としては，maa, Mをmatrixとして与えられているとき，
assertthat::assert_that(rownames(caa)==rownames(maa))
assertthat::assert_that(rownames(caa)==rownames(M))
assertthat::assert_that(colnames(caa)==colnames(maa))
assertthat::assert_that(colnames(caa)==colnames(M))
というようなことになるでしょうか？　@Rindrics さん，assrtthatはこんな感じの使い方でいいですか？

ほかにも引き数の型や形式など，気づいたところからassertthatしていきたいので，他にも必要なところあったら適宜コードを追加していただけると助かります．

**Comment by Rindrics** [comment]
`assertthat::assert_that()`の中は、コンマ区切りで複数の想定を入れられたと思います。
```
assert_that(
  想定1,
  想定2,
  想定3
)
```

`has_name()`というのがあるんですが、`rowname`だと残念ながら使えないかもしれないですね。
