### ISSUE TITLE
ベクトルをスカラーに変更

### ISSUE THREAD

**Issue by KoHMB** [ichimomo/frasyr#504]
```
  if(res$input$use.index == "all"){
    used_index <- res$input$dat$index
  } else {
    used_index <- res$input$dat$index[res$input$use.index,]
  } # 7月7日加筆（浜辺）vpa関数の引数use.index対策
```

`res$input$use.index`にベクトルが入っているとき、warning messageが出る
動作に問題ないので、担当者はvpa関数実行後の以下警告文は無視してかまわない
```
警告メッセージ: 
1:  if (res$input$use.index == "all") { で: 
   条件が長さが 2 以上なので、最初の 1 つだけが使われます 

```

https://github.com/ichimomo/frasyr/blob/5322288ab133f48ac1f6a18291ef5ebf4a39adfd/R/diagnostics_vpa.R#L598-L602

**Comment by KoheiHAMABE** [comment]
assert_thatまで加えたので問題ないと思う
クローズします

**Comment by KoHMB** [comment]
assert_thatまで加えたので問題ないと思う
クローズします
