### ISSUE TITLE
栽培対象種のVPA年のdeviance の計算

### ISSUE THREAD

**Issue by YuuhoYamashita** [ichimomo/frasyr#506]
栽培対象種で自己相関を入れる場合の将来予測の deviance の計算について。
栽培対象種（放流がある資源）ではVPAの加入尾数に放流分の加入も含まれています。
ここで、deviance を計算する時にこのVPAの加入尾数から計算されているようなのですが、再生産式の推定に使ったデータ（天然再生産分のみの加入尾数データで置き換えたdata_SRの値）から計算するように変更してもらえませんでしょうか？

これ、自己相関が入る場合のみなのですが、将来予測初年の deviance の計算にVPA最終年のdeviance × rhoが入ってくるので、少し値が異なってしまいます。どうぞよろしくお願い致します。

**Comment by ichimomo** [comment]
ちょっと複雑な問題になっちゃいますね、、
https://github.com/ichimomo/frasyr_tool/issues/265
とあわせて、どう対処するか考えようと思います。

**Comment by YuuhoYamashita** [comment]
すみません。よろしくお願いいたします。
VPAの値自体を置き換えてしまうと、Fだったか漁獲量だったかに影響が出てしまうんですよね、、、

SR_mat　の　intercept　に過去年の年別放流加入尾数を入れて計算に使用する、とか？
