### ISSUE TITLE
vpa結果の出力ファイルが不完全　v2.1.3.0

### ISSUE THREAD

**Issue by symuko** [ichimomo/frasyr#527]
v2.1.3.0で計算したvpaの結果をsaveした出力ファイル （.rdaファイル）の形式が不完全なようです。ファイルサイズが小さくなっています（例：通常は9kbだが、v2.1.3.0で作ったファイルは7kb)。

1do_MSYestで.rdaファイルを読み込むと、スクリプトは最後まで走り、コンソール画面にもMSYテーブルなどの結果が出力されるのですが、allresults.csvには再生産関係式以降の結果が保存されません。

なお、2021年1月12日現在のdev版でsaveした.rdaファイルは、1do_MSYestで問題なく計算＆結果保存できました。

**Comment by mmitsuyo** [comment]
ご指摘ありがとうございます．
v.2.1.3.0でvpaを行う際には，library(testthat)を追加する必要があることを明記するのを忘れておりました．
大変申し訳ありません．
devにあるバージョンではこの問題は解決されているので，library(testthat)がなくても正常に走ります．
