### ISSUE TITLE
plus.group=FALSEの時でも、グラフに”2+”のようにプラスグループ表示が残る。

### ISSUE THREAD

**Issue by YodaMari** [ichimomo/frasyr#551]
plus.group=FALSEの時、グラフを描くと
年齢表示に"2+"などのプラスグループ表示が残ります。

graph_yield_curve_detail.png
graph_fcurrent.png

今のところ関数の中身を変更しないと表示を変えられないのですが、
オプションで設定できると助かります。

どうぞよろしくお願いいたします。

**Comment by ichimomo** [comment]
こちら対応しました．plot_yieldにplus_groupオプションを追加しています．
toolのほうはこんなかんじ
https://github.com/ichimomo/frasyr_tool/pull/302/files
で変更してください
