### ISSUE TITLE
レジーム分割の場合、allresultsに係数が出力されない

### ISSUE THREAD

**Issue by Hino8ruhiko** [ichimomo/frasyr#554]
最新版(426f94b)でレジーム分割した試算をした場合、allresultsのSR fit resutlsに係数が出力されないようです。係数はres_SR_MSY$regime_parsから確認できますが、allresultsで確認できるようにして頂けますと有難いです。よろしくお願いいたします。

**Comment by ichimomo** [comment]
issueにあげてくださってありがとうございます．↑で対応しましたので，issueをcloseします．この変更についてfrasyrを再インストールさえしていただければtoolのほうは直さなくても変更が反映されるはずです．
どうぞよろしくお願いいたします．
