### ISSUE TITLE
TYPOがあります

### ISSUE THREAD

**Issue by sayokoisu** [ichimomo/frasyr#62]
コピペしたときエラーになりました。
他の方もつまずくかもしれないので、念のためIssue登録します。
お時間のある時に、修正おねがいします。

https://github.com/ichimomo/frasyr/blame/master/README.md#L8

**Comment by ichimomo** [comment]
ありがとうございます。
https://github.com/ichimomo/frasyr/commit/e6c10f52b35ee6897dd098e58a101413770dbcab
修正いたしました。
