### ISSUE TITLE
1歳, 10歳, 2歳, ... 問題

### ISSUE THREAD

**Issue by KoHMB** [ichimomo/frasyr#627]
ggplotだと1歳10歳2歳と表記がなってしまう

`as.factor`とかあれこれする必要あり

ただしモデル診断関数は下流の方だから、上流の`plot_vpa`関数から弄る必要ありか？

**Comment by osamusakai** [comment]
VPA診断のジャックナイフ解析で、このような図になってしまうんですね↓
![Fig_vpa_jackknife_JKplot_par](https://user-images.githubusercontent.com/5091111/122855935-f703d500-d350-11eb-9b58-0e96540b0c6e.png)

VPA本体の（というよりMSY管理基準値の検討の際の）スクリプトでも、似たような問題があります↓
![graph_fcurrent](https://user-images.githubusercontent.com/5091111/122856118-36cabc80-d351-11eb-8938-804c54a97412.png)

**Comment by ichimomo** [comment]
上流のほうでなくても，下流のほうで
mutate(age=factor(age, levels=sort(age))) 
とかにすればいいのでは？

Fcurrentの図のほうはわたしの担当ですね　私も対応します

**Comment by ichimomo** [comment]
あ，または，VPAデータをtibble形式に直す関数（convert_vpa_tibble）のところで，fageみたいなカテゴリを創設してfactor化したageのデータをくっつけますかね？（もともとのageはnumericのまま残しておかないとエラーが起こりそうで怖いので追加で）

**Comment by ichimomo** [comment]
ちなみに，上の図で９歳がないのはなんでですか？こちらについては解決済みですか？

**Comment by osamusakai** [comment]
ワードファイルにコメントしたように、私もジャックナイフ診断で9歳の情報が描画されず困惑しています。
age9とage10（本当はage10+と表記して頂いた方が良いけど）が同じ情報になるので、片方消す仕様になっているのかなと想像しているのですけど・・・。

**Comment by KoHMB** [comment]
age9が映らないのはもともとの仕様です
@osamusakai さんのご指摘の通り、`alpha=1`なので、除いてあります
https://ichimomo.github.io/frasyr/articles/Diagnostics-for-VPA.html#5-

**Comment by KoHMB** [comment]
これも映るように追加したほうがいいでしょうか？

ちなみにこうなっている理由として、VPAの出力の中で`res$term.f`が自然と9歳とか抜けてしまうので、そのままコーディングしたため、こういった形になっています
`res$faa`から抜くだけですので、こちらもすぐに対応できます
https://github.com/ichimomo/frasyr/blob/94746b2a91b3affea6b52a660f8121ee84f2f4ea/R/diagnostics_vpa.R#L1074

**Comment by osamusakai** [comment]
alphaが1ではない資源を扱っている方もいらっしゃると思うので、プラスグループ-1歳（この場合age9）も映るようにしておくと汎用性（統一性？）があって良いかな、と個人的には思いました。冗長と思う方もいるかもしれませんが。

**Comment by KoHMB** [comment]
承知しました　そのように対応します
またマージし次第ご連絡します

**Comment by KoHMB** [comment]
ジャックナイフ法での年齢の表記順について、これで解決しているかと思います
再度インストールし直してご確認頂けますと幸いです

**Comment by osamusakai** [comment]
どうもありがとうございました。
9歳の後に10歳が表示されるようになりました。
![Fig_vpa_jackknife_JKplot_par](https://user-images.githubusercontent.com/5091111/123040945-90a1b400-d42f-11eb-9272-acedafe66ee6.png)

欲を言えば、プラスグループを考慮しているモデルの場合には最大年齢の表記の後に「+」も付いていると嬉しいですが、優先順位は凄く低い話だと思いますので、お時間あるときにご検討頂けますと幸いです。

**Comment by KoHMB** [comment]
＋グループの場合に＋と表記する旨、issueに上げました
お言葉に甘えまして、後日対応させて頂きます
