### ISSUE TITLE
jitterの作図

### ISSUE THREAD

**Issue by ichimomo** [ichimomo/frasyr#631]
jitterの結果の作図ですが，この行でプロットするyの最大値を制限してしまってますよね
https://github.com/ichimomo/frasyr/blob/ea12fd3e562dcd2f4c5e586a485f1662675a47a0/R/diagnostics_vpa.R#L534
でも，このjitterの結果の図は大きく値が外れたFがあるかどうかを確認するための図なので，このような上限設定は，本来の意図から外れるものではないでしょうか？

＝＞上限設定しないように変更したほうが良いかと思います

**Comment by KoHMB** [comment]
確かにそうですね
修正します

**Comment by KoHMB** [comment]
初期値によっては結果が収束しない場合にも、それらのデータを除いて作図されるように修正
