### ISSUE TITLE
est.MSYで使用される世代時間

### ISSUE THREAD

**Issue by ShotaNishijima** [ichimomo/frasyr#65]
est.MSYで使用される世代時間が何年かって取り出せますでしょうか？
自動的に計算されますが、その結果は出ないのではないかと思いますし、Generation.Timeという関数もexportされていないので使えないのかなと思います。
世代時間が何年で、何年後のMSYが計算されているのか、わかるといいかと思いました。
もうちょっと根本的には、futureの引数のうち引き継がれていない（上書きされている）設定（シミュレーション回数とかシミュレーション年）が、分かるようにしたほうがいいかもしれません（メッセージを吐き出すようにするとかして）。

**Comment by ichimomo** [comment]
- v1.20以下のバージョンでは，est.MSYの引数nyearに何も与えないと自動的に世代時間を計算してその20倍の年をMSY計算年にするようにしていました
- v1.20より大きいバージョンではnyearを明示的に与える必要があります．何も与えないとfuture.vpaの実施したときの年数のときのMSYを使います．指定年数をブラックボックス化するのを防ぐためと，frayr_toolを使うのが前提のためです
