### ISSUE TITLE
一部のabund設定(abund=SSB,Bs)においてtmb=FALSEとTRUEでterm.fの推定が微妙に異なる

### ISSUE THREAD

**Issue by mmitsuyo** [ichimomo/frasyr#669]

**Comment by mmitsuyo** [comment]
https://github.com/ichimomo/frasyr/blob/93aabcaeba5271072af994c5b4e457174cda905e/tests/testthat/test-data.handler.R#L572-L574
と
https://github.com/ichimomo/frasyr/blob/93aabcaeba5271072af994c5b4e457174cda905e/tests/testthat/test-data.handler.R#L581-L583
で，term.Fが微妙に違う．（すみません，no.est=TRUEに今はしているので，推定されるときはこのオプションなくしてください）

さらに，abund=Bsのとき（下記）
https://github.com/ichimomo/frasyr/blob/93aabcaeba5271072af994c5b4e457174cda905e/tests/testthat/test-data.handler.R#L586-L588
と
https://github.com/ichimomo/frasyr/blob/93aabcaeba5271072af994c5b4e457174cda905e/tests/testthat/test-data.handler.R#L595-L597
ではterm.Fがさらに違う．

プログラムには問題はないので，恐らくTMBの収束基準が少し甘いのかもしれない．

**Comment by mmitsuyo** [comment]
西嶋さん，issue_669というブランチをつくりました．すみませんが，ご対応のほど宜しくお願い致します．

**Comment by ShotaNishijima** [comment]
@mmitsuyo さん
上のSSBの場合、全部のIndexのabundをSSBにしてしまうと成熟率が0の若齢の情報がないのにその年齢のterminal Fを推定しようとして、そこの推定誤差が大きくなることが推定値の違いを引き起こす原因のようです。3番目と4番目のIndexを"N"としたら一致したので、そのように修正してもいいでしょうか？つまり、vpaの内部関数ではなく設定の問題ということかなと。

**Comment by ShotaNishijima** [comment]
https://github.com/ichimomo/frasyr/pull/671 にて修正&プルリクしましたのでご確認お願いします。

**Comment by mmitsuyo** [comment]
お手数おかけしてすみません．そういうことだったんですね，見落としていました．大変失礼いたしました．ありがとうございました！
