### ISSUE TITLE
pkgdownのエラー解明

### ISSUE THREAD

**Issue by KoHMB** [ichimomo/frasyr#682]
```
 Error: 
  Failed to parse Rd in calc_steepness.Rd
  ℹ subscript out of bounds
Caused by error in `[[`: 
  subscript out of bounds
```

と怒られているので、スティープネス計算周りっぽい

**Comment by KoHMB** [comment]
https://github.com/ichimomo/frasyr/blob/40f4b4a345c59c9a0a116bfd445027535ec462c3/man/calc_steepness.Rd#L50

ここでSRがないってエラーが出る
\dontrun{}の中でもダメなのかな？

**Comment by KoHMB** [comment]
map関数な気がする
前にRmd出力でチルダ形式~にしないと怒られることがあったけどそれに近い気がする（[[だし）

https://github.com/ichimomo/frasyr/blob/40f4b4a345c59c9a0a116bfd445027535ec462c3/R/stock_recruit.r#L2582

**Comment by KoHMB** [comment]
チルダも違う気がしてきたな

- helpの文章出力時のエラーなのか
- そもそもcalc_steepness関数エラーなのか

**Comment by ShotaNishijima** [comment]
https://github.com/ichimomo/frasyr/blob/40f4b4a345c59c9a0a116bfd445027535ec462c3/R/stock_recruit.r#L2497
でSR = SRとなってるからかな？ SR = "HS" とかじゃないと変な気がする。もとはと言えば僕の気がするけどなぜ今さら…

**Comment by KoHMB** [comment]
修正頂いて、ありがとうございます

ただ、そのExampleコードは走らないようになっているから、それほど致命的ではないかなと思います。
自分のローカルで”HS”とかにして`devtools::test`しても怒られた気がします

**Comment by ShotaNishijima** [comment]
テストでエラー出ますか？エラーが再現できなくて

**Comment by ShotaNishijima** [comment]
テストしたけどエラー出ないですね。エラーはここだけ
`Error (test-utilities.R:110:3): calc.rel.abund
Error:  '<ef>ｻ<bf>age' に不正なマルチバイト文字があります `

**Comment by KoHMB** [comment]
今、西嶋さんのdevをこちらでもpullして、`devtools::test`してみましたが、

```
Skip (test-srr-part.R:79:1): output value check
Reason: empty test
---------------------------------------------------------------------------------------
/ |   0       | stock-recruit-part           
  parse(con, n = -1, srcfile = srcfile, encoding = "UTF-8") でエラー: 
   構文解析中に不正なマルチバイト文字列がありました (436 行) 
 追加情報:  18 件の警告がありました (警告を見るには warnings() を使って下さい)
```

`test-srr-part.R`ファイルに全角スペースとか特に何んですけどね…

**Comment by KoHMB** [comment]
`test-stock-recruit-part.R`にも特に全角とかなさそうですが

**Comment by KoHMB** [comment]
上記エラーはここで日本語あるからだと思います
https://github.com/ichimomo/frasyr/blob/f07833a699885121a8403993e70775eb3b5f82d5/tests/testthat/test-stock-recruit-part.R#L436

**Comment by ShotaNishijima** [comment]
それはこう変えたらエラー出なくなりました
https://github.com/ShotaNishijima/frasyr/commit/4dccfb362a250d4e8b85fc451d246da002ed03c4#

**Comment by ShotaNishijima** [comment]
とりあえずcalc_steepness関連のエラーは解消されたんですかね？

**Comment by KoHMB** [comment]
ローカルでの`devtools::test`はエラー出なくなりました
ありがとうございます

ただ、ここのissue自体がichimomoにマージしてみないと分からなくて
フォーク先の環境だと、R-CMDのGitHub Actionsしか実行されないみたいで、pkgdownのActionsを動かさないと一番上のエラーは出てこないんですよね…

**Comment by ShotaNishijima** [comment]
なるほど…。

**Comment by KoHMB** [comment]
https://github.com/ichimomo/frasyr/runs/4147089506?check_suite_focus=true
西嶋さんのマージしてみたけど、GitHub Actionsのpkgdownは相変わらず…

**Comment by ShotaNishijima** [comment]
ありがとう。お役に立てず申し訳ないです。

**Comment by ichimomo** [comment]
JK-junkinさんが解決してくれたのでclose．ありがとうございました！！

**Comment by KoHMB** [comment]
@JK-junkin さん、ありがとうございます！！
