### ISSUE TITLE
R version4.1.1でリッジVPAにエラー

### ISSUE THREAD

**Issue by YodaMari** [ichimomo/frasyr#686]
R version4.1.1　にて
penalty="f"または"s"にすると

 Error in get(stat.tf) : first argument has length > 1

というエラーが出ます。

R version 3.6.1では同じコードでエラーが出ずに計算できることを確認しました。
R version 4.0.2でも計算できているそうです。

**Comment by ichimomo** [comment]
issueに投稿ありがとうございます

R4.1.0から (https://cran.r-project.org/bin/windows/base/old/4.1.0/NEWS.R-4.1.0.html ) 以下のように，getに渡す引き数の長さが2以上だったらエラーを出すように変更されたようですね

![image](https://user-images.githubusercontent.com/44047915/140266562-ab5cb843-7f9a-4813-b010-f593c7b70094.png)

エラーが出ている場所はここだと思いますが，もともとstat.tfは関数内ではベクトルとして扱われている一方で，ここではgetに与えるstat.tfは長さ１のベクトルであることを前提とされたコードなっています
https://github.com/ichimomo/frasyr/blob/f07833a699885121a8403993e70775eb3b5f82d5/R/rvpa.r#L1279-L1281

VPA部分なので，VPA担当の　@mmitsuyo さん，修正いただけないでしょうか？　どうぞよろしくお願いします

**Comment by ichimomo** [comment]
つまり，リッジ，かつ，tf.statを年齢別に変えるような設定をしていた場合には，その設定はいままで効いていなかったということになるかと思います（レアな設定なのでないとは思いますが，，）

**Comment by YodaMari** [comment]
ご対応ありがとうございます。
最新版（83ee5b）をインストールして再計算してみたのですが、
同じエラーが出ているようです。
どうぞよろしくお願いいたします。

**Comment by mmitsuyo** [comment]
まだプルリクしただけで，devにマージされていないからだと思います．もう少しお待ちください．

**Comment by mmitsuyo** [comment]
遅くなりましたが，devにマージしました．これでエラーが出ずに動くでしょうか．

**Comment by YodaMari** [comment]
ありがとうございます。
エラーコード出ずに動きました！
いろいろお手数おかけしました。
