### ISSUE TITLE
TMB=TRUEのときno.est=TRUEオプションが機能しない

### ISSUE THREAD

**Issue by ShotaNishijima** [ichimomo/frasyr#687]
`vpa(..., TMB=TRUE, ... no.est=TRUE)`にしても推定されてしまう。自分で`TMB=FALSE`にすればいいだけですが、一応issueにあげておきます。

**Comment by mmitsuyo** [comment]
西嶋さん，ありがとうございます

**Comment by ShotaNishijima** [comment]
あげといて、こんなん誰かにお願いするものでもないなと思い…。しかし、エラーが…
