### ISSUE TITLE
plog_kobe_ggでplot.yearを指定するとエラー

### ISSUE THREAD

**Issue by ShotaNishijima** [ichimomo/frasyr#690]
vpaの結果の最終年のFがゼロ (last.catch.zero=TRUE) になっていて、そこをプロットからは外したいのですが、
plot_kobe_gg(..., plot.year=1970:2020)
とすると、
```
Error: Problem with `mutate()` column `year_group`.
i `year_group = ifelse(year >= diff.year[i], year_group + 1, year_group)`.
i `year_group` must be size 51 or 1, not 0.
```
というエラーが出るので修正中

**Comment by ichimomo** [comment]
diff.yearというのが，レジームが異なる場合の点を繋げない，ためのコントロール変数なので，そのへん注意していただければと思います．

**Comment by ichimomo** [comment]
なんかそのへん，西嶋さんが修正されたあとにdiff.year関連がコメントアウトされて，また私が元に戻したという経緯が..

これですね
https://github.com/ichimomo/frasyr/issues/641

たぶん，last.catch.zeroと共存するようなコーディングが必要なんだと思います

**Comment by ichimomo** [comment]
あでも，last.catch.zeroとかは実質的には関係ないんですね　すみませんが適当によろしくお願いします

**Comment by ShotaNishijima** [comment]
https://github.com/ichimomo/frasyr/pull/689/commits/8a8ea123a18e7c9a516daec4a3a6ef09260c131f
ここで修正しました。一応、最後の年を抜いた場合と途中の年を抜いた場合、両方でうまくいきそうなことは確認しました
