### ISSUE TITLE
table9_risk作成時のエラー

### ISSUE THREAD

**Issue by symuko** [ichimomo/frasyr#755]
frasyr @f0e0c11でtable9_riskの作成時にエラーが出ます。
> table9_risk <- rank_HCR(table23, unlist(target.prob[,1]), unlist(target.prob[,2]),
+                         target_prob_name=  performance_name[[1] .... [TRUNCATED]
 if (target_threshold[1] < target_threshold[2]) target_threshold[1] <- Inf でエラー:
   TRUE/FALSE が必要なところが欠損値です

代替ルールを検討する魚種の計算にそろそろ入りますので、お忙しいところ申し訳ありませんが、
エラー対処のほどよろしくお願いいたします。

**Comment by ichimomo** [comment]
最新のfrasyrとfrasyr_toolのスクリプトを使われているでしょうか？
例データ＆ダウンロード直後の設定を変えていないままだったら走るけど，データを変えたり設定を変えたりしたら走らないなど，もう少し詳細を教えていただけるとありがたいです．（例データ＆ダウンロード直後の設定を変えていないままだったら，動くはずなんですが．．）

2022年7月27日(水) 16:49 symuko ***@***.***>:

**Comment by YodaMari** [comment]
#+ risk_table_setting ----
## kobeII table の要約表(リスク表、表9)でピックアップする数値の設定
## 管理開始年を0年目として、何年目の数字をピックアップするかを指定する

の設定のところで、年数を調整するとエラーが出るようです。
デフォルトの設定だと大丈夫です。

> target.prob <- table23 %>%
+   arrange(HCR_name) %>%
+   dplyr::filter(HCR_name=="beta50"|(HCR_name=="0.8" & Type=="Base")) %>%    
+   select(perfo .... [TRUNCATED] 
Error in `select()`:
! Can't subset columns that don't exist.
✖ Column `prob_min_any_ssb_2024.2031` doesn't exist.
Run `rlang::last_error()` to see where the error occurred.
> table9_risk <- rank_HCR(table23, unlist(target.prob[,1]), unlist(target.prob[,2]),
+                         target_prob_name=  performance_name[[1]],
+                         risk_prob_name  =  performance_name[[7]]) %>%
+   select(category, everything())
Error in `summary_HCR[risk_prob_name]`:
! Can't subset columns that don't exist.
✖ Column `prob_min_any_ssb_2024.2031` doesn't exist.
Run `rlang::last_error()` to see where the error occurred.

> if(sort_risk_table==TRUE) table9_risk <- table9_risk %>% arrange(Type, desc(category),desc(performance_name[[4]]))
> #' ### HCRまとめ表 ----
> knitr::kable(table9_risk)
Error in knitr::kable(table9_risk) : object 'table9_risk' not found
