### ISSUE TITLE
out.vpa()でfresが定義されていないとエラーで動かない

### ISSUE THREAD

**Issue by fshin3** [ichimomo/frasyr#78]
out.vpa()にvpa関数の結果オブジェクトres_vpaを突っ込んだ時、futureの手順まで進んでいなければfresが作られず、
エラー：オブジェクト`fres`がありません
となって動作しない。

**Comment by ichimomo** [comment]
けっこう前に修正したバグになります．最新版のfrasyrを試してみてください．
