### ISSUE TITLE
リッジVPAの自動化

### ISSUE THREAD

**Issue by KoHMB** [ichimomo/frasyr#797]
リッジVPAのλの探索を自動で行う関数を作る
引数としては、VPAの設定、レトロで何を見るか、その辺かと思う

**Comment by KoHMB** [comment]
概ね作れた気がする。etaの方も対応している。

以下対応できていないこと
- ペナルティ探索時にFAAごとにMohn's rhoを用いている場合（e.g. スケトウ太平洋、日本海）
- ペナルティ探索法をMohn’s rhoではなく平均二乗誤差率(RMSPE)を使っている場合（e.g. スケトウ太平洋）
- Ｆのペナルティの影響が大きく、lambdaが0.99とか上限突破する対処療法（e.g. スケトウ太平洋のα, Fの比と別のパラメータ）

**Comment by mmitsuyo** [comment]
濱邉さん，ご対応ありがとうございます．あとで確認してみます．

**Comment by mmitsuyo** [comment]
大変遅くなってしまいすみません，確認させていただきました．
濱邉さんが書かれているように，個々の系群における特殊な設定については未対応ですが，一般的なλとηの探索自動化の関数はこれでよいと思うのでいったん，プルリク＆マージさせていただきます．個別な対応について必要な場合は別途相談ということで宜しくお願い致します．濱邉さん，ありがとうございました．

**Comment by mmitsuyo** [comment]
https://github.com/ichimomo/frasyr/pull/804#issue-1755779726
