### ISSUE TITLE
yield curveの色

### ISSUE THREAD

**Issue by ichimomo** [ichimomo/frasyr#802]
10歳以上の年齢がある場合には色わけがなされない場合がある？
ちょっと調べて，修正すること

**Comment by shingowatari** [comment]
> 10歳以上の年齢がある場合には色わけがなされない場合がある？ ちょっと調べて，修正すること
先日の魚種別作業部会のスライド23枚目のように4年齢群の色が抜けています。キンメダイの例です。
https://fra2015.sharepoint.com/:p:/s/ABCWG/EeusYkZ6I1dEsCfrDZYuZRsBgRBRaIrp6rxlBF1HIioHCQ?e=cHmaYo
