### ISSUE TITLE
vignette (frasyrの使い方例) がRで読めない

### ISSUE THREAD

**Issue by JK-junkin** [ichimomo/frasyr#81]
`vignette(package = "frasyr")`を実行すると`no vignettes found`となる。

とりあえずの対応として、
1. https://github.com/ichimomo/frasyr/tree/master/vignettes から直接Rmdファイルをダウンロードし（あるいはrepositoryごとクローンして）
1. RStudioでファイルを開き（たとえばvpa.Rmd）
1. `knitr`パッケージを使ってKnit（Sourceペイン上方のKnitボタンを押す。あるいはMacなら**Shift + Cmd + K**, Windowsなら**Shift + Ctrl + K**かな?）して表示している。

### 動作環境
 |setting | value |
|---|---|
 |version | R version 3.6.1 (2019-07-05)|
 |os | macOS Mojave 10.14.6 |
 |system | x86_64, darwin15.6.0 |
 |ui | RStudio |
 |language | (EN) |
 |collate | ja_JP.UTF-8|
 |ctype | ja_JP.UTF-8|
 |tz | Asia/Tokyo |
 |date | 2019-10-29|

**Comment by ichimomo** [comment]
ご報告ありがとうございます．私もvignetteが読めない問題，気づいていていろいろ調べたんですが，なかなか解決できず困っています（環境依存ではなさそう）．もしよい解決法ありましたら教えてください．

また，vignetteの内容は以下のリンク先のものと同一ですので，当面はこのリンク先を見る感じにしてください．
https://github.com/ichimomo/frasyr#%E3%83%9E%E3%83%8B%E3%83%A5%E3%82%A2%E3%83%AB

**Comment by JK-junkin** [comment]
ご返信くださり、ありがとうございます。
htlmページのリンクを見る旨、承知しました。

わかりました。forkして問題検証してみます。

**Comment by JK-junkin** [comment]
### 自分のための気づきメモ
1. ~~もしかすると、`install_github()`はソースパッケージをインストールするため、vignetteがビルドされてないのかも。`frasyr`をバンドルパッケージ化 (`devtools::build()`か) すれば、vignetteが読めるようになるかも。参考：『Rパッケージ開発入門』p.19~~ 否。`install_github()`は`build()`に橋渡す設計のようだ。
1. inst/doc/ (を作成して) vignette/の中身を移したらどうなるか。試してみよう。

**Comment by AnguillaJaponica** [comment]
no vignettes foundとあるので、ビルドしてあげると見られるようになります(手元で試しましたが、表示されました。環境はMacです)

![image](https://user-images.githubusercontent.com/47109605/70844804-87727700-1e89-11ea-9cb1-40b4665d9c09.png)

```install_github()```はデフォルトだとvignettesをビルドしてくれないので、```build_vignettes=TRUE```オプションをつけて実行します。うまく行かなかった場合は、以下のサイトを参照していじってみると行けるかと思います。

https://github.com/STAT545-UBC/Discussion/issues/68
http://r-pkgs.had.co.nz/vignettes.html

また、手動でディレクトリを増やして・ファイルを移して...をやるのはあまりおすすめしません。独自の運用が積み重なっていくうちに保守がきかないパッケージになることがあります。

**Comment by JK-junkin** [comment]
> install_github()でビルドする場合はデフォルトだとvignettesをビルドしてくれないので、build_vignettes=TRUEオプションをつけて実行します。うまく行かなかった場合は、以下のサイトを参照していじってみると行けるかと思います。
知りませんでした。ありがとうございます。

> ただ、inst/doc以下にはvignetteのファイルを置くことはあまりおすすめされていません(『Rパッケージ開発入門』p.179にも記載されてあります)。全てvignettes以下に格納してください。パッケージ構造として、vignettesのソースはhtmlやpdfとしてinst/docにビルドされてからdoc/にインストールされるという道筋をたどるため、最初からinst/docに格納されると期待する結果が起きない/予期しない動作が起きる可能性があると思います。

ありがとうございます！勉強になりました。

**Comment by AnguillaJaponica** [comment]
お役に立てれば何よりです。おかげさまで、私も諸々調べなおす良い機会をいただけました。

もし問題なくvingnettesがRで表示されるようになりましたら、closeしてください。

**Comment by JK-junkin** [comment]
`devtools::install_github("ichimomo/frasyr", build_vignettes = T)`
で`vignette`が読めるようになりました (#161 の効果かもしれませんが)。
ありがとうございました。Issueを閉じます。

**Comment by ichimomo** [comment]
いまさらですが過去のご投稿ありがとうございます．ようやくvignetteにまで手が回るようになり，勉強させていただいています．．

**Comment by AnguillaJaponica** [comment]
いえ、そんなお恥ずかしい限りです。。大きな/複雑なプロジェクトをまわされており大変なことと存じます。陰ながら応援いたしております。

(P.S 少し前の話になりますが、先生の作られたfish_game、プレイしました。バックエンドはもとより、プレイヤーが子どもであることを念頭においた最初の説明文やUIに、細やかな配慮を感じました(簡単なようで誰にでもできることではないと思ってます)。イサキを選ばれているのも嬉しいです。イサキ好きでして。)

**Comment by ichimomo** [comment]
あ、あのゲームやってくれたんですね、、。コロナで子供と自宅勤務しているときにこういうのあったらいいなとおもって作って、けっこう苦労した割には家族にリリースしたあと別の仕事が忙しくなって最近放置気味のものです。。。shinyRは便利ですが、shinyapps.ioで公開しようとするとggplot内の日本語が文字化けしてしまうのが日本人向けのユーザーフレンドリーなソフトを作るときにはけっこうな障害になりますよね。。（fishgameでは最低限の文字を画像にしてはりつけてますが）

**Comment by AnguillaJaponica** [comment]
とても素敵だと思います。

私は職業柄fish_gameクリアでユーザーにMSC認証商品など資源を考慮した商品のクーポンを発行してマーケティングに使う方法とか考えてました。持続可能性を商品の強みとする企業と、そういうゲームをやってみ/せようという顧客は良いマッチングかなと。水族館などにQRコードを貼り、親御さんのスマホを使ってお子さんがゲームをし、そのまま親御さんにクーポンを使って商品を買ってもらうと共に、食育に役立てていただく。あとは仕入先と在庫管理、と。

そうすると、今度は水産資源学をキッチリ勉強してハックしてくる人間が出てくるので、FRAの優秀な研究者たちが初期尾数の調整から確率的な資源変動、果ては漁業者同士のゲーム理論を用いたモデルまで使い始め...。冗談です。

私は文字コードの処理にはよくぶつかりますね。。(日本語だったり、絵文字だったり...)
ECサイトに入力される文字列の処理から、鮮魚小売店のレシートのテキストデータまで幅広くやってますが、しょっちゅうつまづいてます。
