### ISSUE TITLE
plot_residual_vpa() でSSBが横軸のとき散布図回帰がずれる？

### ISSUE THREAD

**Issue by JK-junkin** [ichimomo/frasyr#812]
@ichimomo 様、@mmitsuyo 様

![スクリーンショット 2023-07-03 15 43 17](https://github.com/ichimomo/frasyr/assets/50478487/08903f85-9146-4596-a038-bdfd26cc5c29)

お世話になっております。
frasyrのplot_residual_vpa() でSSBに対するフィットを確認していたところ、添付した図の右列下から2番目のパネル（index02、SSBをチューニングした指標値) のように散布図とのフィットがよくありませんでした。一方で、時系列のフィットは問題なさそうであるため（index02、右列の他のパネル）、推定結果が正しいのか逡巡しているところです。

R/diagnostics_vpa.r の649行目に `#res$ssbはスケーリングしていない結果が出ている(2021/06/09KoHMB)` という記述があったのですが、これが関係していたりするのでしょうか。

ご多用のところ恐縮ですが、ご確認いただけましたら幸いです。

**Comment by ichimomo** [comment]
ご報告ありがとうございます。
本問題が出るときにVPAではどのおうなオプションを使っているか教えていただけないでしょうか？

**Comment by JK-junkin** [comment]
@ichimomo さま、@KoHMB さま

お返事をくださりありがとうございます。
下記のような設定で`vap()`を実施しています。

```
    out <- frasyr::vpa(tmpdat,
        tune       = TRUE,
        sel.update = FALSE,
        tf.year    = 2019:2021, # centering年
        term.F     = "all",
        stat.tf    = "mean",
        sel.def    = "max",
        scale      = 1,
        abund      = c("N", "N", "SSB"),
        min.age    = c(0, 0, 1),
        max.age    = c(0, 0, 3),
        use.index  = c(2, 3),
        b.est      = TRUE,
        lambda     = 0.7,
        penalty    = "f",
        est.method = "ml",
        Pope       = TRUE,
        p.init     = 0.75,
        p.pope     = 0.5,
        plus.group = FALSE,
        alpha      = 1,
        fc.year    = 2020:2022 # 将来予測用.
    )
```

入力値tmpdatの親魚量の単位はトンです。最小5桁、最大7桁（2万トン〜100万トン超) です。
親魚量に当てている指標値は規格化した値で、0〜3の範囲です。
