### ISSUE TITLE
ジャックナイフ法のバグ修正

### ISSUE THREAD

**Issue by KoHMB** [ichimomo/frasyr#819]
以下、res_tmp1とres_tmp2が一致しない
```
i = 4 ; res = res_vpa_estb
input0 <- res$input
input0$dat$index <- res$input$dat$index[-i,]
input0$abund <- input0$abund[-i]
input0$plot <- FALSE
input0$sigma.const <- input0$sigma.const[-i]
input0$sigma.constraint <- input0$sigma.constraint[-i]
res_tmp1 <- safe_call(vpa, input0, force=TRUE)

input0$min.age <- input0$min.age[-i]
input0$max.age <- input0$max.age[-i]
res_tmp2 <- safe_call(vpa, input0, force=TRUE)
```

**Comment by KoHMB** [comment]
関数の方、修正加えてみました。どうしても、use.index引数の長さだけ変えると警告メッセージ出るのが嫌な感じですね。
改めての確認ですが、use.indexをコントロールすれば、abundやmin.age引数なども自動で反映される（以前のジャックナイフ関数のようにあえて手動で各引数から取り除く必要がない）か、ご確認頂けますと幸いです。

**Comment by mmitsuyo** [comment]
返信遅れてすみません．確認しました．
まずuse.indexについてですが，濱邉さんのご認識で正しいです．
use.indexをコントロールすれば、abundやmin.age引数なども自動で反映されるので，濱邉さんの修正で正しいかと思います．

警告に関しては，ご存知かと思いますが，https://github.com/ichimomo/frasyr/pull/811#issue-1777992418
で新たに木下さんのご提案で付け加えたwarningかと思います．
VPAでuse.indexを指定しているときに指標の数と同じだけのlinkやabun,min.ageなどの引数を最初に指定しておかないと，気づかないうちに変な参照がされてしまうことを避けるために，ここでwarningを入れて下さったのだと認識しています．
jackknifeをやるたびにこの警告が出るのもそのためで，上記で述べたことさえちゃんとしていれば，気にする必要のないwarningかと思います．

**Comment by KoHMB** [comment]
明日中に対応しますので、少々お待ちください

**Comment by KoHMB** [comment]
マージされたので、こちらクローズします

**Comment by KoHMB** [comment]
マージされたので、こちらクローズします
