### ISSUE TITLE
`average_SR_mat()` <-> `set_SR_mat()` 間に循環参照がある

### ISSUE THREAD

**Issue by Rindrics** [ichimomo/frasyr#883]
関数間に循環参照を見つけたので一応お知らせです 🙏 

- [`average_SR_mat()`](https://github.com/ichimomo/frasyr/blob/fab19598e25a1f466be02c7eb41a1ecd76c44675/R/future.r#L1425)
- [`set_SR_mat()`](https://github.com/ichimomo/frasyr/blob/fab19598e25a1f466be02c7eb41a1ecd76c44675/R/future.r#L1085)

<img width="233" alt="image" src="https://github.com/user-attachments/assets/df398195-090e-4e34-893c-b2be42c504b9">

現状のままでも特に問題なければ本 issue は close してしまってください！

**Comment by ichimomo** [comment]
ありがとうございます！確認してみましたが、 average_SR_matから再度set_SR_matに戻る際には、average_SR_matに行かないようにオプションを買えているので、（たぶん）大丈夫と思います ^_^ !
